// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gateway.proto
#ifndef GRPC_gateway_2eproto__INCLUDED
#define GRPC_gateway_2eproto__INCLUDED

#include "gateway.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace otrader {

// Gateway service: runs in Gateway process; Runtime is client.
class GatewayService final {
 public:
  static constexpr char const* service_full_name() {
    return "otrader.GatewayService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Connect(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> AsyncConnect(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(AsyncConnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> PrepareAsyncConnect(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(PrepareAsyncConnectRaw(context, request, cq));
    }
    virtual ::grpc::Status Disconnect(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> AsyncDisconnect(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(AsyncDisconnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> PrepareAsyncDisconnect(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(PrepareAsyncDisconnectRaw(context, request, cq));
    }
    virtual ::grpc::Status SendOrder(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg& request, ::otrader::OrderIdResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::OrderIdResponse>> AsyncSendOrder(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::OrderIdResponse>>(AsyncSendOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::OrderIdResponse>> PrepareAsyncSendOrder(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::OrderIdResponse>>(PrepareAsyncSendOrderRaw(context, request, cq));
    }
    virtual ::grpc::Status CancelOrder(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg& request, ::otrader::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> AsyncCancelOrder(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(AsyncCancelOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> PrepareAsyncCancelOrder(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(PrepareAsyncCancelOrderRaw(context, request, cq));
    }
    virtual ::grpc::Status QueryAccount(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> AsyncQueryAccount(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(AsyncQueryAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> PrepareAsyncQueryAccount(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(PrepareAsyncQueryAccountRaw(context, request, cq));
    }
    virtual ::grpc::Status QueryPosition(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> AsyncQueryPosition(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(AsyncQueryPositionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> PrepareAsyncQueryPosition(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(PrepareAsyncQueryPositionRaw(context, request, cq));
    }
    // Streams: Gateway pushes to Runtime
    std::unique_ptr< ::grpc::ClientReaderInterface< ::otrader::OrderDataMsg>> StreamOrderUpdates(::grpc::ClientContext* context, const ::otrader::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::otrader::OrderDataMsg>>(StreamOrderUpdatesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::otrader::OrderDataMsg>> AsyncStreamOrderUpdates(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::otrader::OrderDataMsg>>(AsyncStreamOrderUpdatesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::otrader::OrderDataMsg>> PrepareAsyncStreamOrderUpdates(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::otrader::OrderDataMsg>>(PrepareAsyncStreamOrderUpdatesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::otrader::TradeDataMsg>> StreamTradeUpdates(::grpc::ClientContext* context, const ::otrader::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::otrader::TradeDataMsg>>(StreamTradeUpdatesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::otrader::TradeDataMsg>> AsyncStreamTradeUpdates(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::otrader::TradeDataMsg>>(AsyncStreamTradeUpdatesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::otrader::TradeDataMsg>> PrepareAsyncStreamTradeUpdates(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::otrader::TradeDataMsg>>(PrepareAsyncStreamTradeUpdatesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Connect(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Connect(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Disconnect(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Disconnect(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SendOrder(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg* request, ::otrader::OrderIdResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendOrder(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg* request, ::otrader::OrderIdResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void CancelOrder(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CancelOrder(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void QueryAccount(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void QueryAccount(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void QueryPosition(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void QueryPosition(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Streams: Gateway pushes to Runtime
      virtual void StreamOrderUpdates(::grpc::ClientContext* context, const ::otrader::Empty* request, ::grpc::ClientReadReactor< ::otrader::OrderDataMsg>* reactor) = 0;
      virtual void StreamTradeUpdates(::grpc::ClientContext* context, const ::otrader::Empty* request, ::grpc::ClientReadReactor< ::otrader::TradeDataMsg>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* AsyncConnectRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* PrepareAsyncConnectRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* AsyncDisconnectRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* PrepareAsyncDisconnectRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::OrderIdResponse>* AsyncSendOrderRaw(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::OrderIdResponse>* PrepareAsyncSendOrderRaw(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* AsyncCancelOrderRaw(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* PrepareAsyncCancelOrderRaw(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* AsyncQueryAccountRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* PrepareAsyncQueryAccountRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* AsyncQueryPositionRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* PrepareAsyncQueryPositionRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::otrader::OrderDataMsg>* StreamOrderUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::otrader::OrderDataMsg>* AsyncStreamOrderUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::otrader::OrderDataMsg>* PrepareAsyncStreamOrderUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::otrader::TradeDataMsg>* StreamTradeUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::otrader::TradeDataMsg>* AsyncStreamTradeUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::otrader::TradeDataMsg>* PrepareAsyncStreamTradeUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Connect(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> AsyncConnect(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(AsyncConnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> PrepareAsyncConnect(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(PrepareAsyncConnectRaw(context, request, cq));
    }
    ::grpc::Status Disconnect(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> AsyncDisconnect(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(AsyncDisconnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> PrepareAsyncDisconnect(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(PrepareAsyncDisconnectRaw(context, request, cq));
    }
    ::grpc::Status SendOrder(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg& request, ::otrader::OrderIdResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::OrderIdResponse>> AsyncSendOrder(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::OrderIdResponse>>(AsyncSendOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::OrderIdResponse>> PrepareAsyncSendOrder(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::OrderIdResponse>>(PrepareAsyncSendOrderRaw(context, request, cq));
    }
    ::grpc::Status CancelOrder(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg& request, ::otrader::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> AsyncCancelOrder(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(AsyncCancelOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> PrepareAsyncCancelOrder(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(PrepareAsyncCancelOrderRaw(context, request, cq));
    }
    ::grpc::Status QueryAccount(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> AsyncQueryAccount(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(AsyncQueryAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> PrepareAsyncQueryAccount(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(PrepareAsyncQueryAccountRaw(context, request, cq));
    }
    ::grpc::Status QueryPosition(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> AsyncQueryPosition(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(AsyncQueryPositionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> PrepareAsyncQueryPosition(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(PrepareAsyncQueryPositionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::otrader::OrderDataMsg>> StreamOrderUpdates(::grpc::ClientContext* context, const ::otrader::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::otrader::OrderDataMsg>>(StreamOrderUpdatesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::otrader::OrderDataMsg>> AsyncStreamOrderUpdates(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::otrader::OrderDataMsg>>(AsyncStreamOrderUpdatesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::otrader::OrderDataMsg>> PrepareAsyncStreamOrderUpdates(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::otrader::OrderDataMsg>>(PrepareAsyncStreamOrderUpdatesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::otrader::TradeDataMsg>> StreamTradeUpdates(::grpc::ClientContext* context, const ::otrader::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::otrader::TradeDataMsg>>(StreamTradeUpdatesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::otrader::TradeDataMsg>> AsyncStreamTradeUpdates(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::otrader::TradeDataMsg>>(AsyncStreamTradeUpdatesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::otrader::TradeDataMsg>> PrepareAsyncStreamTradeUpdates(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::otrader::TradeDataMsg>>(PrepareAsyncStreamTradeUpdatesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Connect(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) override;
      void Connect(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Disconnect(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) override;
      void Disconnect(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SendOrder(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg* request, ::otrader::OrderIdResponse* response, std::function<void(::grpc::Status)>) override;
      void SendOrder(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg* request, ::otrader::OrderIdResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CancelOrder(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) override;
      void CancelOrder(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void QueryAccount(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) override;
      void QueryAccount(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void QueryPosition(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) override;
      void QueryPosition(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamOrderUpdates(::grpc::ClientContext* context, const ::otrader::Empty* request, ::grpc::ClientReadReactor< ::otrader::OrderDataMsg>* reactor) override;
      void StreamTradeUpdates(::grpc::ClientContext* context, const ::otrader::Empty* request, ::grpc::ClientReadReactor< ::otrader::TradeDataMsg>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* AsyncConnectRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* PrepareAsyncConnectRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* AsyncDisconnectRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* PrepareAsyncDisconnectRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::OrderIdResponse>* AsyncSendOrderRaw(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::OrderIdResponse>* PrepareAsyncSendOrderRaw(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* AsyncCancelOrderRaw(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* PrepareAsyncCancelOrderRaw(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* AsyncQueryAccountRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* PrepareAsyncQueryAccountRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* AsyncQueryPositionRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* PrepareAsyncQueryPositionRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::otrader::OrderDataMsg>* StreamOrderUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request) override;
    ::grpc::ClientAsyncReader< ::otrader::OrderDataMsg>* AsyncStreamOrderUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::otrader::OrderDataMsg>* PrepareAsyncStreamOrderUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::otrader::TradeDataMsg>* StreamTradeUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request) override;
    ::grpc::ClientAsyncReader< ::otrader::TradeDataMsg>* AsyncStreamTradeUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::otrader::TradeDataMsg>* PrepareAsyncStreamTradeUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Connect_;
    const ::grpc::internal::RpcMethod rpcmethod_Disconnect_;
    const ::grpc::internal::RpcMethod rpcmethod_SendOrder_;
    const ::grpc::internal::RpcMethod rpcmethod_CancelOrder_;
    const ::grpc::internal::RpcMethod rpcmethod_QueryAccount_;
    const ::grpc::internal::RpcMethod rpcmethod_QueryPosition_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamOrderUpdates_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamTradeUpdates_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Connect(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response);
    virtual ::grpc::Status Disconnect(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response);
    virtual ::grpc::Status SendOrder(::grpc::ServerContext* context, const ::otrader::OrderRequestMsg* request, ::otrader::OrderIdResponse* response);
    virtual ::grpc::Status CancelOrder(::grpc::ServerContext* context, const ::otrader::CancelRequestMsg* request, ::otrader::Empty* response);
    virtual ::grpc::Status QueryAccount(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response);
    virtual ::grpc::Status QueryPosition(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response);
    // Streams: Gateway pushes to Runtime
    virtual ::grpc::Status StreamOrderUpdates(::grpc::ServerContext* context, const ::otrader::Empty* request, ::grpc::ServerWriter< ::otrader::OrderDataMsg>* writer);
    virtual ::grpc::Status StreamTradeUpdates(::grpc::ServerContext* context, const ::otrader::Empty* request, ::grpc::ServerWriter< ::otrader::TradeDataMsg>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_Connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Connect() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Connect(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConnect(::grpc::ServerContext* context, ::otrader::Empty* request, ::grpc::ServerAsyncResponseWriter< ::otrader::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Disconnect() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDisconnect(::grpc::ServerContext* context, ::otrader::Empty* request, ::grpc::ServerAsyncResponseWriter< ::otrader::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SendOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendOrder() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_SendOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendOrder(::grpc::ServerContext* /*context*/, const ::otrader::OrderRequestMsg* /*request*/, ::otrader::OrderIdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendOrder(::grpc::ServerContext* context, ::otrader::OrderRequestMsg* request, ::grpc::ServerAsyncResponseWriter< ::otrader::OrderIdResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CancelOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CancelOrder() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_CancelOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelOrder(::grpc::ServerContext* /*context*/, const ::otrader::CancelRequestMsg* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancelOrder(::grpc::ServerContext* context, ::otrader::CancelRequestMsg* request, ::grpc::ServerAsyncResponseWriter< ::otrader::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_QueryAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_QueryAccount() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_QueryAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryAccount(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryAccount(::grpc::ServerContext* context, ::otrader::Empty* request, ::grpc::ServerAsyncResponseWriter< ::otrader::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_QueryPosition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_QueryPosition() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_QueryPosition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryPosition(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryPosition(::grpc::ServerContext* context, ::otrader::Empty* request, ::grpc::ServerAsyncResponseWriter< ::otrader::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamOrderUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamOrderUpdates() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_StreamOrderUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamOrderUpdates(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::OrderDataMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamOrderUpdates(::grpc::ServerContext* context, ::otrader::Empty* request, ::grpc::ServerAsyncWriter< ::otrader::OrderDataMsg>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(6, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamTradeUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamTradeUpdates() {
      ::grpc::Service::MarkMethodAsync(7);
    }
    ~WithAsyncMethod_StreamTradeUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamTradeUpdates(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::TradeDataMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamTradeUpdates(::grpc::ServerContext* context, ::otrader::Empty* request, ::grpc::ServerAsyncWriter< ::otrader::TradeDataMsg>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(7, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Connect<WithAsyncMethod_Disconnect<WithAsyncMethod_SendOrder<WithAsyncMethod_CancelOrder<WithAsyncMethod_QueryAccount<WithAsyncMethod_QueryPosition<WithAsyncMethod_StreamOrderUpdates<WithAsyncMethod_StreamTradeUpdates<Service > > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Connect() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::otrader::Empty, ::otrader::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) { return this->Connect(context, request, response); }));}
    void SetMessageAllocatorFor_Connect(
        ::grpc::MessageAllocator< ::otrader::Empty, ::otrader::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::otrader::Empty, ::otrader::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Connect(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Connect(
      ::grpc::CallbackServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Disconnect() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::otrader::Empty, ::otrader::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) { return this->Disconnect(context, request, response); }));}
    void SetMessageAllocatorFor_Disconnect(
        ::grpc::MessageAllocator< ::otrader::Empty, ::otrader::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::otrader::Empty, ::otrader::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Disconnect(
      ::grpc::CallbackServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SendOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendOrder() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::otrader::OrderRequestMsg, ::otrader::OrderIdResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::otrader::OrderRequestMsg* request, ::otrader::OrderIdResponse* response) { return this->SendOrder(context, request, response); }));}
    void SetMessageAllocatorFor_SendOrder(
        ::grpc::MessageAllocator< ::otrader::OrderRequestMsg, ::otrader::OrderIdResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::otrader::OrderRequestMsg, ::otrader::OrderIdResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendOrder(::grpc::ServerContext* /*context*/, const ::otrader::OrderRequestMsg* /*request*/, ::otrader::OrderIdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::otrader::OrderRequestMsg* /*request*/, ::otrader::OrderIdResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CancelOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CancelOrder() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::otrader::CancelRequestMsg, ::otrader::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::otrader::CancelRequestMsg* request, ::otrader::Empty* response) { return this->CancelOrder(context, request, response); }));}
    void SetMessageAllocatorFor_CancelOrder(
        ::grpc::MessageAllocator< ::otrader::CancelRequestMsg, ::otrader::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::otrader::CancelRequestMsg, ::otrader::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CancelOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelOrder(::grpc::ServerContext* /*context*/, const ::otrader::CancelRequestMsg* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CancelOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::otrader::CancelRequestMsg* /*request*/, ::otrader::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_QueryAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_QueryAccount() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::otrader::Empty, ::otrader::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) { return this->QueryAccount(context, request, response); }));}
    void SetMessageAllocatorFor_QueryAccount(
        ::grpc::MessageAllocator< ::otrader::Empty, ::otrader::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::otrader::Empty, ::otrader::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_QueryAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryAccount(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* QueryAccount(
      ::grpc::CallbackServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_QueryPosition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_QueryPosition() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::otrader::Empty, ::otrader::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) { return this->QueryPosition(context, request, response); }));}
    void SetMessageAllocatorFor_QueryPosition(
        ::grpc::MessageAllocator< ::otrader::Empty, ::otrader::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::otrader::Empty, ::otrader::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_QueryPosition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryPosition(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* QueryPosition(
      ::grpc::CallbackServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamOrderUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamOrderUpdates() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackServerStreamingHandler< ::otrader::Empty, ::otrader::OrderDataMsg>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::otrader::Empty* request) { return this->StreamOrderUpdates(context, request); }));
    }
    ~WithCallbackMethod_StreamOrderUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamOrderUpdates(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::OrderDataMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::otrader::OrderDataMsg>* StreamOrderUpdates(
      ::grpc::CallbackServerContext* /*context*/, const ::otrader::Empty* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamTradeUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamTradeUpdates() {
      ::grpc::Service::MarkMethodCallback(7,
          new ::grpc::internal::CallbackServerStreamingHandler< ::otrader::Empty, ::otrader::TradeDataMsg>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::otrader::Empty* request) { return this->StreamTradeUpdates(context, request); }));
    }
    ~WithCallbackMethod_StreamTradeUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamTradeUpdates(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::TradeDataMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::otrader::TradeDataMsg>* StreamTradeUpdates(
      ::grpc::CallbackServerContext* /*context*/, const ::otrader::Empty* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Connect<WithCallbackMethod_Disconnect<WithCallbackMethod_SendOrder<WithCallbackMethod_CancelOrder<WithCallbackMethod_QueryAccount<WithCallbackMethod_QueryPosition<WithCallbackMethod_StreamOrderUpdates<WithCallbackMethod_StreamTradeUpdates<Service > > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Connect() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Connect(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Disconnect() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SendOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendOrder() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_SendOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendOrder(::grpc::ServerContext* /*context*/, const ::otrader::OrderRequestMsg* /*request*/, ::otrader::OrderIdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CancelOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CancelOrder() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_CancelOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelOrder(::grpc::ServerContext* /*context*/, const ::otrader::CancelRequestMsg* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_QueryAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_QueryAccount() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_QueryAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryAccount(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_QueryPosition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_QueryPosition() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_QueryPosition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryPosition(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamOrderUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamOrderUpdates() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_StreamOrderUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamOrderUpdates(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::OrderDataMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamTradeUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamTradeUpdates() {
      ::grpc::Service::MarkMethodGeneric(7);
    }
    ~WithGenericMethod_StreamTradeUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamTradeUpdates(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::TradeDataMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Connect() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Connect(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConnect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Disconnect() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDisconnect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendOrder() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_SendOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendOrder(::grpc::ServerContext* /*context*/, const ::otrader::OrderRequestMsg* /*request*/, ::otrader::OrderIdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendOrder(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CancelOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CancelOrder() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_CancelOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelOrder(::grpc::ServerContext* /*context*/, const ::otrader::CancelRequestMsg* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancelOrder(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_QueryAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_QueryAccount() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_QueryAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryAccount(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryAccount(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_QueryPosition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_QueryPosition() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_QueryPosition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryPosition(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryPosition(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamOrderUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamOrderUpdates() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_StreamOrderUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamOrderUpdates(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::OrderDataMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamOrderUpdates(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(6, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamTradeUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamTradeUpdates() {
      ::grpc::Service::MarkMethodRaw(7);
    }
    ~WithRawMethod_StreamTradeUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamTradeUpdates(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::TradeDataMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamTradeUpdates(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(7, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Connect() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Connect(context, request, response); }));
    }
    ~WithRawCallbackMethod_Connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Connect(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Connect(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Disconnect() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Disconnect(context, request, response); }));
    }
    ~WithRawCallbackMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Disconnect(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendOrder() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendOrder(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendOrder(::grpc::ServerContext* /*context*/, const ::otrader::OrderRequestMsg* /*request*/, ::otrader::OrderIdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CancelOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CancelOrder() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CancelOrder(context, request, response); }));
    }
    ~WithRawCallbackMethod_CancelOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelOrder(::grpc::ServerContext* /*context*/, const ::otrader::CancelRequestMsg* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CancelOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_QueryAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_QueryAccount() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->QueryAccount(context, request, response); }));
    }
    ~WithRawCallbackMethod_QueryAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryAccount(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* QueryAccount(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_QueryPosition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_QueryPosition() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->QueryPosition(context, request, response); }));
    }
    ~WithRawCallbackMethod_QueryPosition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryPosition(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* QueryPosition(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamOrderUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamOrderUpdates() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamOrderUpdates(context, request); }));
    }
    ~WithRawCallbackMethod_StreamOrderUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamOrderUpdates(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::OrderDataMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamOrderUpdates(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamTradeUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamTradeUpdates() {
      ::grpc::Service::MarkMethodRawCallback(7,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamTradeUpdates(context, request); }));
    }
    ~WithRawCallbackMethod_StreamTradeUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamTradeUpdates(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::TradeDataMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamTradeUpdates(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Connect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Connect() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::otrader::Empty, ::otrader::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::otrader::Empty, ::otrader::Empty>* streamer) {
                       return this->StreamedConnect(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Connect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Connect(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedConnect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::otrader::Empty,::otrader::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Disconnect() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::otrader::Empty, ::otrader::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::otrader::Empty, ::otrader::Empty>* streamer) {
                       return this->StreamedDisconnect(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDisconnect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::otrader::Empty,::otrader::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendOrder() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::otrader::OrderRequestMsg, ::otrader::OrderIdResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::otrader::OrderRequestMsg, ::otrader::OrderIdResponse>* streamer) {
                       return this->StreamedSendOrder(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendOrder(::grpc::ServerContext* /*context*/, const ::otrader::OrderRequestMsg* /*request*/, ::otrader::OrderIdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendOrder(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::otrader::OrderRequestMsg,::otrader::OrderIdResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CancelOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CancelOrder() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::otrader::CancelRequestMsg, ::otrader::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::otrader::CancelRequestMsg, ::otrader::Empty>* streamer) {
                       return this->StreamedCancelOrder(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CancelOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CancelOrder(::grpc::ServerContext* /*context*/, const ::otrader::CancelRequestMsg* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCancelOrder(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::otrader::CancelRequestMsg,::otrader::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_QueryAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_QueryAccount() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::otrader::Empty, ::otrader::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::otrader::Empty, ::otrader::Empty>* streamer) {
                       return this->StreamedQueryAccount(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_QueryAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status QueryAccount(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedQueryAccount(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::otrader::Empty,::otrader::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_QueryPosition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_QueryPosition() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::otrader::Empty, ::otrader::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::otrader::Empty, ::otrader::Empty>* streamer) {
                       return this->StreamedQueryPosition(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_QueryPosition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status QueryPosition(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedQueryPosition(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::otrader::Empty,::otrader::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Connect<WithStreamedUnaryMethod_Disconnect<WithStreamedUnaryMethod_SendOrder<WithStreamedUnaryMethod_CancelOrder<WithStreamedUnaryMethod_QueryAccount<WithStreamedUnaryMethod_QueryPosition<Service > > > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamOrderUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamOrderUpdates() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::otrader::Empty, ::otrader::OrderDataMsg>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::otrader::Empty, ::otrader::OrderDataMsg>* streamer) {
                       return this->StreamedStreamOrderUpdates(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamOrderUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamOrderUpdates(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::OrderDataMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamOrderUpdates(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::otrader::Empty,::otrader::OrderDataMsg>* server_split_streamer) = 0;
  };
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamTradeUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamTradeUpdates() {
      ::grpc::Service::MarkMethodStreamed(7,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::otrader::Empty, ::otrader::TradeDataMsg>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::otrader::Empty, ::otrader::TradeDataMsg>* streamer) {
                       return this->StreamedStreamTradeUpdates(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamTradeUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamTradeUpdates(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::TradeDataMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamTradeUpdates(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::otrader::Empty,::otrader::TradeDataMsg>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamOrderUpdates<WithSplitStreamingMethod_StreamTradeUpdates<Service > > SplitStreamedService;
  typedef WithStreamedUnaryMethod_Connect<WithStreamedUnaryMethod_Disconnect<WithStreamedUnaryMethod_SendOrder<WithStreamedUnaryMethod_CancelOrder<WithStreamedUnaryMethod_QueryAccount<WithStreamedUnaryMethod_QueryPosition<WithSplitStreamingMethod_StreamOrderUpdates<WithSplitStreamingMethod_StreamTradeUpdates<Service > > > > > > > > StreamedService;
};

}  // namespace otrader


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_gateway_2eproto__INCLUDED
