// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gateway.proto

#include "gateway.pb.h"
#include "gateway.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace otrader {

static const char* GatewayService_method_names[] = {
  "/otrader.GatewayService/Connect",
  "/otrader.GatewayService/Disconnect",
  "/otrader.GatewayService/SendOrder",
  "/otrader.GatewayService/CancelOrder",
  "/otrader.GatewayService/QueryAccount",
  "/otrader.GatewayService/QueryPosition",
  "/otrader.GatewayService/StreamOrderUpdates",
  "/otrader.GatewayService/StreamTradeUpdates",
};

std::unique_ptr< GatewayService::Stub> GatewayService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GatewayService::Stub> stub(new GatewayService::Stub(channel, options));
  return stub;
}

GatewayService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Connect_(GatewayService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Disconnect_(GatewayService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendOrder_(GatewayService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CancelOrder_(GatewayService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryAccount_(GatewayService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryPosition_(GatewayService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamOrderUpdates_(GatewayService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_StreamTradeUpdates_(GatewayService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status GatewayService::Stub::Connect(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Connect_, context, request, response);
}

void GatewayService::Stub::async::Connect(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Connect_, context, request, response, std::move(f));
}

void GatewayService::Stub::async::Connect(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Connect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* GatewayService::Stub::PrepareAsyncConnectRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Connect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* GatewayService::Stub::AsyncConnectRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConnectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GatewayService::Stub::Disconnect(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Disconnect_, context, request, response);
}

void GatewayService::Stub::async::Disconnect(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Disconnect_, context, request, response, std::move(f));
}

void GatewayService::Stub::async::Disconnect(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Disconnect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* GatewayService::Stub::PrepareAsyncDisconnectRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Disconnect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* GatewayService::Stub::AsyncDisconnectRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDisconnectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GatewayService::Stub::SendOrder(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg& request, ::otrader::OrderIdResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::OrderRequestMsg, ::otrader::OrderIdResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendOrder_, context, request, response);
}

void GatewayService::Stub::async::SendOrder(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg* request, ::otrader::OrderIdResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::OrderRequestMsg, ::otrader::OrderIdResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendOrder_, context, request, response, std::move(f));
}

void GatewayService::Stub::async::SendOrder(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg* request, ::otrader::OrderIdResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::OrderIdResponse>* GatewayService::Stub::PrepareAsyncSendOrderRaw(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::OrderIdResponse, ::otrader::OrderRequestMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendOrder_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::OrderIdResponse>* GatewayService::Stub::AsyncSendOrderRaw(::grpc::ClientContext* context, const ::otrader::OrderRequestMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendOrderRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GatewayService::Stub::CancelOrder(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::CancelRequestMsg, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CancelOrder_, context, request, response);
}

void GatewayService::Stub::async::CancelOrder(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::CancelRequestMsg, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelOrder_, context, request, response, std::move(f));
}

void GatewayService::Stub::async::CancelOrder(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* GatewayService::Stub::PrepareAsyncCancelOrderRaw(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::CancelRequestMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CancelOrder_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* GatewayService::Stub::AsyncCancelOrderRaw(::grpc::ClientContext* context, const ::otrader::CancelRequestMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCancelOrderRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GatewayService::Stub::QueryAccount(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryAccount_, context, request, response);
}

void GatewayService::Stub::async::QueryAccount(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryAccount_, context, request, response, std::move(f));
}

void GatewayService::Stub::async::QueryAccount(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* GatewayService::Stub::PrepareAsyncQueryAccountRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* GatewayService::Stub::AsyncQueryAccountRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GatewayService::Stub::QueryPosition(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryPosition_, context, request, response);
}

void GatewayService::Stub::async::QueryPosition(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryPosition_, context, request, response, std::move(f));
}

void GatewayService::Stub::async::QueryPosition(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryPosition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* GatewayService::Stub::PrepareAsyncQueryPositionRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryPosition_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* GatewayService::Stub::AsyncQueryPositionRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryPositionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::otrader::OrderDataMsg>* GatewayService::Stub::StreamOrderUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::otrader::OrderDataMsg>::Create(channel_.get(), rpcmethod_StreamOrderUpdates_, context, request);
}

void GatewayService::Stub::async::StreamOrderUpdates(::grpc::ClientContext* context, const ::otrader::Empty* request, ::grpc::ClientReadReactor< ::otrader::OrderDataMsg>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::otrader::OrderDataMsg>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamOrderUpdates_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::otrader::OrderDataMsg>* GatewayService::Stub::AsyncStreamOrderUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::otrader::OrderDataMsg>::Create(channel_.get(), cq, rpcmethod_StreamOrderUpdates_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::otrader::OrderDataMsg>* GatewayService::Stub::PrepareAsyncStreamOrderUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::otrader::OrderDataMsg>::Create(channel_.get(), cq, rpcmethod_StreamOrderUpdates_, context, request, false, nullptr);
}

::grpc::ClientReader< ::otrader::TradeDataMsg>* GatewayService::Stub::StreamTradeUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::otrader::TradeDataMsg>::Create(channel_.get(), rpcmethod_StreamTradeUpdates_, context, request);
}

void GatewayService::Stub::async::StreamTradeUpdates(::grpc::ClientContext* context, const ::otrader::Empty* request, ::grpc::ClientReadReactor< ::otrader::TradeDataMsg>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::otrader::TradeDataMsg>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamTradeUpdates_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::otrader::TradeDataMsg>* GatewayService::Stub::AsyncStreamTradeUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::otrader::TradeDataMsg>::Create(channel_.get(), cq, rpcmethod_StreamTradeUpdates_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::otrader::TradeDataMsg>* GatewayService::Stub::PrepareAsyncStreamTradeUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::otrader::TradeDataMsg>::Create(channel_.get(), cq, rpcmethod_StreamTradeUpdates_, context, request, false, nullptr);
}

GatewayService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GatewayService::Service, ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GatewayService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::Empty* resp) {
               return service->Connect(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GatewayService::Service, ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GatewayService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::Empty* resp) {
               return service->Disconnect(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GatewayService::Service, ::otrader::OrderRequestMsg, ::otrader::OrderIdResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GatewayService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::OrderRequestMsg* req,
             ::otrader::OrderIdResponse* resp) {
               return service->SendOrder(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GatewayService::Service, ::otrader::CancelRequestMsg, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GatewayService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::CancelRequestMsg* req,
             ::otrader::Empty* resp) {
               return service->CancelOrder(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GatewayService::Service, ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GatewayService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::Empty* resp) {
               return service->QueryAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GatewayService::Service, ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GatewayService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::Empty* resp) {
               return service->QueryPosition(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayService_method_names[6],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< GatewayService::Service, ::otrader::Empty, ::otrader::OrderDataMsg>(
          [](GatewayService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::grpc::ServerWriter<::otrader::OrderDataMsg>* writer) {
               return service->StreamOrderUpdates(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayService_method_names[7],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< GatewayService::Service, ::otrader::Empty, ::otrader::TradeDataMsg>(
          [](GatewayService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::grpc::ServerWriter<::otrader::TradeDataMsg>* writer) {
               return service->StreamTradeUpdates(ctx, req, writer);
             }, this)));
}

GatewayService::Service::~Service() {
}

::grpc::Status GatewayService::Service::Connect(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GatewayService::Service::Disconnect(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GatewayService::Service::SendOrder(::grpc::ServerContext* context, const ::otrader::OrderRequestMsg* request, ::otrader::OrderIdResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GatewayService::Service::CancelOrder(::grpc::ServerContext* context, const ::otrader::CancelRequestMsg* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GatewayService::Service::QueryAccount(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GatewayService::Service::QueryPosition(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GatewayService::Service::StreamOrderUpdates(::grpc::ServerContext* context, const ::otrader::Empty* request, ::grpc::ServerWriter< ::otrader::OrderDataMsg>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GatewayService::Service::StreamTradeUpdates(::grpc::ServerContext* context, const ::otrader::Empty* request, ::grpc::ServerWriter< ::otrader::TradeDataMsg>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace otrader
#include <grpcpp/ports_undef.inc>

