// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: marketdata.proto
#ifndef GRPC_marketdata_2eproto__INCLUDED
#define GRPC_marketdata_2eproto__INCLUDED

#include "marketdata.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace otrader {

// Market Data service: runs in Market Data process; Runtime is client.
class MarketDataService final {
 public:
  static constexpr char const* service_full_name() {
    return "otrader.MarketDataService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Start(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> AsyncStart(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(AsyncStartRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> PrepareAsyncStart(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(PrepareAsyncStartRaw(context, request, cq));
    }
    virtual ::grpc::Status Stop(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> AsyncStop(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(AsyncStopRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> PrepareAsyncStop(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(PrepareAsyncStopRaw(context, request, cq));
    }
    virtual ::grpc::Status SubscribeChains(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest& request, ::otrader::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> AsyncSubscribeChains(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(AsyncSubscribeChainsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> PrepareAsyncSubscribeChains(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(PrepareAsyncSubscribeChainsRaw(context, request, cq));
    }
    virtual ::grpc::Status UnsubscribeChains(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest& request, ::otrader::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> AsyncUnsubscribeChains(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(AsyncUnsubscribeChainsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>> PrepareAsyncUnsubscribeChains(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>>(PrepareAsyncUnsubscribeChainsRaw(context, request, cq));
    }
    // Stream: Market Data pushes snapshots to Runtime
    std::unique_ptr< ::grpc::ClientReaderInterface< ::otrader::PortfolioSnapshotMsg>> StreamSnapshots(::grpc::ClientContext* context, const ::otrader::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::otrader::PortfolioSnapshotMsg>>(StreamSnapshotsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::otrader::PortfolioSnapshotMsg>> AsyncStreamSnapshots(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::otrader::PortfolioSnapshotMsg>>(AsyncStreamSnapshotsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::otrader::PortfolioSnapshotMsg>> PrepareAsyncStreamSnapshots(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::otrader::PortfolioSnapshotMsg>>(PrepareAsyncStreamSnapshotsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Start(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Start(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Stop(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Stop(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SubscribeChains(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SubscribeChains(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void UnsubscribeChains(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UnsubscribeChains(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Stream: Market Data pushes snapshots to Runtime
      virtual void StreamSnapshots(::grpc::ClientContext* context, const ::otrader::Empty* request, ::grpc::ClientReadReactor< ::otrader::PortfolioSnapshotMsg>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* AsyncStartRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* PrepareAsyncStartRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* AsyncStopRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* PrepareAsyncStopRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* AsyncSubscribeChainsRaw(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* PrepareAsyncSubscribeChainsRaw(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* AsyncUnsubscribeChainsRaw(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::otrader::Empty>* PrepareAsyncUnsubscribeChainsRaw(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::otrader::PortfolioSnapshotMsg>* StreamSnapshotsRaw(::grpc::ClientContext* context, const ::otrader::Empty& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::otrader::PortfolioSnapshotMsg>* AsyncStreamSnapshotsRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::otrader::PortfolioSnapshotMsg>* PrepareAsyncStreamSnapshotsRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Start(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> AsyncStart(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(AsyncStartRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> PrepareAsyncStart(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(PrepareAsyncStartRaw(context, request, cq));
    }
    ::grpc::Status Stop(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> AsyncStop(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(AsyncStopRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> PrepareAsyncStop(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(PrepareAsyncStopRaw(context, request, cq));
    }
    ::grpc::Status SubscribeChains(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest& request, ::otrader::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> AsyncSubscribeChains(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(AsyncSubscribeChainsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> PrepareAsyncSubscribeChains(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(PrepareAsyncSubscribeChainsRaw(context, request, cq));
    }
    ::grpc::Status UnsubscribeChains(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest& request, ::otrader::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> AsyncUnsubscribeChains(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(AsyncUnsubscribeChainsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>> PrepareAsyncUnsubscribeChains(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::otrader::Empty>>(PrepareAsyncUnsubscribeChainsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::otrader::PortfolioSnapshotMsg>> StreamSnapshots(::grpc::ClientContext* context, const ::otrader::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::otrader::PortfolioSnapshotMsg>>(StreamSnapshotsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::otrader::PortfolioSnapshotMsg>> AsyncStreamSnapshots(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::otrader::PortfolioSnapshotMsg>>(AsyncStreamSnapshotsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::otrader::PortfolioSnapshotMsg>> PrepareAsyncStreamSnapshots(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::otrader::PortfolioSnapshotMsg>>(PrepareAsyncStreamSnapshotsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Start(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) override;
      void Start(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Stop(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) override;
      void Stop(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SubscribeChains(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) override;
      void SubscribeChains(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void UnsubscribeChains(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest* request, ::otrader::Empty* response, std::function<void(::grpc::Status)>) override;
      void UnsubscribeChains(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamSnapshots(::grpc::ClientContext* context, const ::otrader::Empty* request, ::grpc::ClientReadReactor< ::otrader::PortfolioSnapshotMsg>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* AsyncStartRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* PrepareAsyncStartRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* AsyncStopRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* PrepareAsyncStopRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* AsyncSubscribeChainsRaw(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* PrepareAsyncSubscribeChainsRaw(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* AsyncUnsubscribeChainsRaw(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::otrader::Empty>* PrepareAsyncUnsubscribeChainsRaw(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::otrader::PortfolioSnapshotMsg>* StreamSnapshotsRaw(::grpc::ClientContext* context, const ::otrader::Empty& request) override;
    ::grpc::ClientAsyncReader< ::otrader::PortfolioSnapshotMsg>* AsyncStreamSnapshotsRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::otrader::PortfolioSnapshotMsg>* PrepareAsyncStreamSnapshotsRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Start_;
    const ::grpc::internal::RpcMethod rpcmethod_Stop_;
    const ::grpc::internal::RpcMethod rpcmethod_SubscribeChains_;
    const ::grpc::internal::RpcMethod rpcmethod_UnsubscribeChains_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamSnapshots_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Start(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response);
    virtual ::grpc::Status Stop(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response);
    virtual ::grpc::Status SubscribeChains(::grpc::ServerContext* context, const ::otrader::SubscribeChainsRequest* request, ::otrader::Empty* response);
    virtual ::grpc::Status UnsubscribeChains(::grpc::ServerContext* context, const ::otrader::UnsubscribeChainsRequest* request, ::otrader::Empty* response);
    // Stream: Market Data pushes snapshots to Runtime
    virtual ::grpc::Status StreamSnapshots(::grpc::ServerContext* context, const ::otrader::Empty* request, ::grpc::ServerWriter< ::otrader::PortfolioSnapshotMsg>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_Start : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Start() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Start() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Start(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStart(::grpc::ServerContext* context, ::otrader::Empty* request, ::grpc::ServerAsyncResponseWriter< ::otrader::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Stop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Stop() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Stop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stop(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStop(::grpc::ServerContext* context, ::otrader::Empty* request, ::grpc::ServerAsyncResponseWriter< ::otrader::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SubscribeChains : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SubscribeChains() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_SubscribeChains() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeChains(::grpc::ServerContext* /*context*/, const ::otrader::SubscribeChainsRequest* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribeChains(::grpc::ServerContext* context, ::otrader::SubscribeChainsRequest* request, ::grpc::ServerAsyncResponseWriter< ::otrader::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UnsubscribeChains : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UnsubscribeChains() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_UnsubscribeChains() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UnsubscribeChains(::grpc::ServerContext* /*context*/, const ::otrader::UnsubscribeChainsRequest* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUnsubscribeChains(::grpc::ServerContext* context, ::otrader::UnsubscribeChainsRequest* request, ::grpc::ServerAsyncResponseWriter< ::otrader::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamSnapshots : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamSnapshots() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_StreamSnapshots() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamSnapshots(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::PortfolioSnapshotMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamSnapshots(::grpc::ServerContext* context, ::otrader::Empty* request, ::grpc::ServerAsyncWriter< ::otrader::PortfolioSnapshotMsg>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(4, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Start<WithAsyncMethod_Stop<WithAsyncMethod_SubscribeChains<WithAsyncMethod_UnsubscribeChains<WithAsyncMethod_StreamSnapshots<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Start : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Start() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::otrader::Empty, ::otrader::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) { return this->Start(context, request, response); }));}
    void SetMessageAllocatorFor_Start(
        ::grpc::MessageAllocator< ::otrader::Empty, ::otrader::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::otrader::Empty, ::otrader::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Start() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Start(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Start(
      ::grpc::CallbackServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Stop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Stop() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::otrader::Empty, ::otrader::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) { return this->Stop(context, request, response); }));}
    void SetMessageAllocatorFor_Stop(
        ::grpc::MessageAllocator< ::otrader::Empty, ::otrader::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::otrader::Empty, ::otrader::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Stop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stop(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Stop(
      ::grpc::CallbackServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SubscribeChains : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SubscribeChains() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::otrader::SubscribeChainsRequest, ::otrader::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::otrader::SubscribeChainsRequest* request, ::otrader::Empty* response) { return this->SubscribeChains(context, request, response); }));}
    void SetMessageAllocatorFor_SubscribeChains(
        ::grpc::MessageAllocator< ::otrader::SubscribeChainsRequest, ::otrader::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::otrader::SubscribeChainsRequest, ::otrader::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SubscribeChains() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeChains(::grpc::ServerContext* /*context*/, const ::otrader::SubscribeChainsRequest* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubscribeChains(
      ::grpc::CallbackServerContext* /*context*/, const ::otrader::SubscribeChainsRequest* /*request*/, ::otrader::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UnsubscribeChains : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UnsubscribeChains() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::otrader::UnsubscribeChainsRequest, ::otrader::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::otrader::UnsubscribeChainsRequest* request, ::otrader::Empty* response) { return this->UnsubscribeChains(context, request, response); }));}
    void SetMessageAllocatorFor_UnsubscribeChains(
        ::grpc::MessageAllocator< ::otrader::UnsubscribeChainsRequest, ::otrader::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::otrader::UnsubscribeChainsRequest, ::otrader::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UnsubscribeChains() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UnsubscribeChains(::grpc::ServerContext* /*context*/, const ::otrader::UnsubscribeChainsRequest* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UnsubscribeChains(
      ::grpc::CallbackServerContext* /*context*/, const ::otrader::UnsubscribeChainsRequest* /*request*/, ::otrader::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamSnapshots : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamSnapshots() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackServerStreamingHandler< ::otrader::Empty, ::otrader::PortfolioSnapshotMsg>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::otrader::Empty* request) { return this->StreamSnapshots(context, request); }));
    }
    ~WithCallbackMethod_StreamSnapshots() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamSnapshots(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::PortfolioSnapshotMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::otrader::PortfolioSnapshotMsg>* StreamSnapshots(
      ::grpc::CallbackServerContext* /*context*/, const ::otrader::Empty* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Start<WithCallbackMethod_Stop<WithCallbackMethod_SubscribeChains<WithCallbackMethod_UnsubscribeChains<WithCallbackMethod_StreamSnapshots<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Start : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Start() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Start() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Start(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Stop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Stop() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Stop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stop(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SubscribeChains : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SubscribeChains() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_SubscribeChains() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeChains(::grpc::ServerContext* /*context*/, const ::otrader::SubscribeChainsRequest* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UnsubscribeChains : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UnsubscribeChains() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_UnsubscribeChains() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UnsubscribeChains(::grpc::ServerContext* /*context*/, const ::otrader::UnsubscribeChainsRequest* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamSnapshots : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamSnapshots() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_StreamSnapshots() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamSnapshots(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::PortfolioSnapshotMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Start : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Start() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Start() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Start(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStart(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Stop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Stop() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Stop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stop(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStop(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SubscribeChains : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SubscribeChains() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_SubscribeChains() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeChains(::grpc::ServerContext* /*context*/, const ::otrader::SubscribeChainsRequest* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubscribeChains(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UnsubscribeChains : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UnsubscribeChains() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_UnsubscribeChains() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UnsubscribeChains(::grpc::ServerContext* /*context*/, const ::otrader::UnsubscribeChainsRequest* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUnsubscribeChains(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamSnapshots : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamSnapshots() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_StreamSnapshots() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamSnapshots(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::PortfolioSnapshotMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamSnapshots(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(4, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Start : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Start() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Start(context, request, response); }));
    }
    ~WithRawCallbackMethod_Start() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Start(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Start(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Stop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Stop() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Stop(context, request, response); }));
    }
    ~WithRawCallbackMethod_Stop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stop(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Stop(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SubscribeChains : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SubscribeChains() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SubscribeChains(context, request, response); }));
    }
    ~WithRawCallbackMethod_SubscribeChains() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubscribeChains(::grpc::ServerContext* /*context*/, const ::otrader::SubscribeChainsRequest* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubscribeChains(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UnsubscribeChains : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UnsubscribeChains() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UnsubscribeChains(context, request, response); }));
    }
    ~WithRawCallbackMethod_UnsubscribeChains() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UnsubscribeChains(::grpc::ServerContext* /*context*/, const ::otrader::UnsubscribeChainsRequest* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UnsubscribeChains(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamSnapshots : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamSnapshots() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamSnapshots(context, request); }));
    }
    ~WithRawCallbackMethod_StreamSnapshots() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamSnapshots(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::PortfolioSnapshotMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamSnapshots(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Start : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Start() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::otrader::Empty, ::otrader::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::otrader::Empty, ::otrader::Empty>* streamer) {
                       return this->StreamedStart(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Start() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Start(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStart(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::otrader::Empty,::otrader::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Stop : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Stop() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::otrader::Empty, ::otrader::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::otrader::Empty, ::otrader::Empty>* streamer) {
                       return this->StreamedStop(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Stop() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Stop(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStop(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::otrader::Empty,::otrader::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SubscribeChains : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SubscribeChains() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::otrader::SubscribeChainsRequest, ::otrader::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::otrader::SubscribeChainsRequest, ::otrader::Empty>* streamer) {
                       return this->StreamedSubscribeChains(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SubscribeChains() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubscribeChains(::grpc::ServerContext* /*context*/, const ::otrader::SubscribeChainsRequest* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSubscribeChains(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::otrader::SubscribeChainsRequest,::otrader::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UnsubscribeChains : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UnsubscribeChains() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::otrader::UnsubscribeChainsRequest, ::otrader::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::otrader::UnsubscribeChainsRequest, ::otrader::Empty>* streamer) {
                       return this->StreamedUnsubscribeChains(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UnsubscribeChains() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UnsubscribeChains(::grpc::ServerContext* /*context*/, const ::otrader::UnsubscribeChainsRequest* /*request*/, ::otrader::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUnsubscribeChains(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::otrader::UnsubscribeChainsRequest,::otrader::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Start<WithStreamedUnaryMethod_Stop<WithStreamedUnaryMethod_SubscribeChains<WithStreamedUnaryMethod_UnsubscribeChains<Service > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamSnapshots : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamSnapshots() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::otrader::Empty, ::otrader::PortfolioSnapshotMsg>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::otrader::Empty, ::otrader::PortfolioSnapshotMsg>* streamer) {
                       return this->StreamedStreamSnapshots(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamSnapshots() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamSnapshots(::grpc::ServerContext* /*context*/, const ::otrader::Empty* /*request*/, ::grpc::ServerWriter< ::otrader::PortfolioSnapshotMsg>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamSnapshots(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::otrader::Empty,::otrader::PortfolioSnapshotMsg>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamSnapshots<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_Start<WithStreamedUnaryMethod_Stop<WithStreamedUnaryMethod_SubscribeChains<WithStreamedUnaryMethod_UnsubscribeChains<WithSplitStreamingMethod_StreamSnapshots<Service > > > > > StreamedService;
};

}  // namespace otrader


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_marketdata_2eproto__INCLUDED
