// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: marketdata.proto

#include "marketdata.pb.h"
#include "marketdata.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace otrader {

static const char* MarketDataService_method_names[] = {
  "/otrader.MarketDataService/Start",
  "/otrader.MarketDataService/Stop",
  "/otrader.MarketDataService/SubscribeChains",
  "/otrader.MarketDataService/UnsubscribeChains",
  "/otrader.MarketDataService/StreamSnapshots",
};

std::unique_ptr< MarketDataService::Stub> MarketDataService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MarketDataService::Stub> stub(new MarketDataService::Stub(channel, options));
  return stub;
}

MarketDataService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Start_(MarketDataService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Stop_(MarketDataService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SubscribeChains_(MarketDataService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UnsubscribeChains_(MarketDataService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamSnapshots_(MarketDataService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status MarketDataService::Stub::Start(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Start_, context, request, response);
}

void MarketDataService::Stub::async::Start(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Start_, context, request, response, std::move(f));
}

void MarketDataService::Stub::async::Start(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Start_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* MarketDataService::Stub::PrepareAsyncStartRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Start_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* MarketDataService::Stub::AsyncStartRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MarketDataService::Stub::Stop(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Stop_, context, request, response);
}

void MarketDataService::Stub::async::Stop(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Stop_, context, request, response, std::move(f));
}

void MarketDataService::Stub::async::Stop(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Stop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* MarketDataService::Stub::PrepareAsyncStopRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Stop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* MarketDataService::Stub::AsyncStopRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MarketDataService::Stub::SubscribeChains(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::SubscribeChainsRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SubscribeChains_, context, request, response);
}

void MarketDataService::Stub::async::SubscribeChains(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::SubscribeChainsRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubscribeChains_, context, request, response, std::move(f));
}

void MarketDataService::Stub::async::SubscribeChains(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubscribeChains_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* MarketDataService::Stub::PrepareAsyncSubscribeChainsRaw(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::SubscribeChainsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SubscribeChains_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* MarketDataService::Stub::AsyncSubscribeChainsRaw(::grpc::ClientContext* context, const ::otrader::SubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSubscribeChainsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MarketDataService::Stub::UnsubscribeChains(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::UnsubscribeChainsRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UnsubscribeChains_, context, request, response);
}

void MarketDataService::Stub::async::UnsubscribeChains(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::UnsubscribeChainsRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnsubscribeChains_, context, request, response, std::move(f));
}

void MarketDataService::Stub::async::UnsubscribeChains(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnsubscribeChains_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* MarketDataService::Stub::PrepareAsyncUnsubscribeChainsRaw(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::UnsubscribeChainsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UnsubscribeChains_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* MarketDataService::Stub::AsyncUnsubscribeChainsRaw(::grpc::ClientContext* context, const ::otrader::UnsubscribeChainsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUnsubscribeChainsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::otrader::PortfolioSnapshotMsg>* MarketDataService::Stub::StreamSnapshotsRaw(::grpc::ClientContext* context, const ::otrader::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::otrader::PortfolioSnapshotMsg>::Create(channel_.get(), rpcmethod_StreamSnapshots_, context, request);
}

void MarketDataService::Stub::async::StreamSnapshots(::grpc::ClientContext* context, const ::otrader::Empty* request, ::grpc::ClientReadReactor< ::otrader::PortfolioSnapshotMsg>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::otrader::PortfolioSnapshotMsg>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamSnapshots_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::otrader::PortfolioSnapshotMsg>* MarketDataService::Stub::AsyncStreamSnapshotsRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::otrader::PortfolioSnapshotMsg>::Create(channel_.get(), cq, rpcmethod_StreamSnapshots_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::otrader::PortfolioSnapshotMsg>* MarketDataService::Stub::PrepareAsyncStreamSnapshotsRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::otrader::PortfolioSnapshotMsg>::Create(channel_.get(), cq, rpcmethod_StreamSnapshots_, context, request, false, nullptr);
}

MarketDataService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MarketDataService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MarketDataService::Service, ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MarketDataService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::Empty* resp) {
               return service->Start(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MarketDataService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MarketDataService::Service, ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MarketDataService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::Empty* resp) {
               return service->Stop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MarketDataService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MarketDataService::Service, ::otrader::SubscribeChainsRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MarketDataService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::SubscribeChainsRequest* req,
             ::otrader::Empty* resp) {
               return service->SubscribeChains(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MarketDataService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MarketDataService::Service, ::otrader::UnsubscribeChainsRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MarketDataService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::UnsubscribeChainsRequest* req,
             ::otrader::Empty* resp) {
               return service->UnsubscribeChains(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MarketDataService_method_names[4],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< MarketDataService::Service, ::otrader::Empty, ::otrader::PortfolioSnapshotMsg>(
          [](MarketDataService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::grpc::ServerWriter<::otrader::PortfolioSnapshotMsg>* writer) {
               return service->StreamSnapshots(ctx, req, writer);
             }, this)));
}

MarketDataService::Service::~Service() {
}

::grpc::Status MarketDataService::Service::Start(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MarketDataService::Service::Stop(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MarketDataService::Service::SubscribeChains(::grpc::ServerContext* context, const ::otrader::SubscribeChainsRequest* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MarketDataService::Service::UnsubscribeChains(::grpc::ServerContext* context, const ::otrader::UnsubscribeChainsRequest* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MarketDataService::Service::StreamSnapshots(::grpc::ServerContext* context, const ::otrader::Empty* request, ::grpc::ServerWriter< ::otrader::PortfolioSnapshotMsg>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace otrader
#include <grpcpp/ports_undef.inc>

