// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: marketdata.proto
// Protobuf C++ Version: 6.33.4

#ifndef marketdata_2eproto_2epb_2eh
#define marketdata_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "otrader_engine.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_marketdata_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_marketdata_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_marketdata_2eproto;
}  // extern "C"
namespace otrader {
class PortfolioSnapshotMsg;
struct PortfolioSnapshotMsgDefaultTypeInternal;
extern PortfolioSnapshotMsgDefaultTypeInternal _PortfolioSnapshotMsg_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PortfolioSnapshotMsg_class_data_;
class SubscribeChainsRequest;
struct SubscribeChainsRequestDefaultTypeInternal;
extern SubscribeChainsRequestDefaultTypeInternal _SubscribeChainsRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SubscribeChainsRequest_class_data_;
class UnsubscribeChainsRequest;
struct UnsubscribeChainsRequestDefaultTypeInternal;
extern UnsubscribeChainsRequestDefaultTypeInternal _UnsubscribeChainsRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull UnsubscribeChainsRequest_class_data_;
}  // namespace otrader
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace otrader {

// ===================================================================


// -------------------------------------------------------------------

class UnsubscribeChainsRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:otrader.UnsubscribeChainsRequest) */ {
 public:
  inline UnsubscribeChainsRequest() : UnsubscribeChainsRequest(nullptr) {}
  ~UnsubscribeChainsRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UnsubscribeChainsRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UnsubscribeChainsRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UnsubscribeChainsRequest(::google::protobuf::internal::ConstantInitialized);

  inline UnsubscribeChainsRequest(const UnsubscribeChainsRequest& from) : UnsubscribeChainsRequest(nullptr, from) {}
  inline UnsubscribeChainsRequest(UnsubscribeChainsRequest&& from) noexcept
      : UnsubscribeChainsRequest(nullptr, ::std::move(from)) {}
  inline UnsubscribeChainsRequest& operator=(const UnsubscribeChainsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline UnsubscribeChainsRequest& operator=(UnsubscribeChainsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UnsubscribeChainsRequest& default_instance() {
    return *reinterpret_cast<const UnsubscribeChainsRequest*>(
        &_UnsubscribeChainsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(UnsubscribeChainsRequest& a, UnsubscribeChainsRequest& b) { a.Swap(&b); }
  inline void Swap(UnsubscribeChainsRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UnsubscribeChainsRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UnsubscribeChainsRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UnsubscribeChainsRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UnsubscribeChainsRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UnsubscribeChainsRequest& from) { UnsubscribeChainsRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UnsubscribeChainsRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "otrader.UnsubscribeChainsRequest"; }

  explicit UnsubscribeChainsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  UnsubscribeChainsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const UnsubscribeChainsRequest& from);
  UnsubscribeChainsRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, UnsubscribeChainsRequest&& from) noexcept
      : UnsubscribeChainsRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStrategyNameFieldNumber = 1,
  };
  // string strategy_name = 1;
  void clear_strategy_name() ;
  const ::std::string& strategy_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_strategy_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_strategy_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_strategy_name();
  void set_allocated_strategy_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_strategy_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_strategy_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_strategy_name();

  public:
  // @@protoc_insertion_point(class_scope:otrader.UnsubscribeChainsRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 54,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const UnsubscribeChainsRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr strategy_name_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_marketdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull UnsubscribeChainsRequest_class_data_;
// -------------------------------------------------------------------

class SubscribeChainsRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:otrader.SubscribeChainsRequest) */ {
 public:
  inline SubscribeChainsRequest() : SubscribeChainsRequest(nullptr) {}
  ~SubscribeChainsRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SubscribeChainsRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SubscribeChainsRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SubscribeChainsRequest(::google::protobuf::internal::ConstantInitialized);

  inline SubscribeChainsRequest(const SubscribeChainsRequest& from) : SubscribeChainsRequest(nullptr, from) {}
  inline SubscribeChainsRequest(SubscribeChainsRequest&& from) noexcept
      : SubscribeChainsRequest(nullptr, ::std::move(from)) {}
  inline SubscribeChainsRequest& operator=(const SubscribeChainsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SubscribeChainsRequest& operator=(SubscribeChainsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SubscribeChainsRequest& default_instance() {
    return *reinterpret_cast<const SubscribeChainsRequest*>(
        &_SubscribeChainsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SubscribeChainsRequest& a, SubscribeChainsRequest& b) { a.Swap(&b); }
  inline void Swap(SubscribeChainsRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SubscribeChainsRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SubscribeChainsRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SubscribeChainsRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SubscribeChainsRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SubscribeChainsRequest& from) { SubscribeChainsRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SubscribeChainsRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "otrader.SubscribeChainsRequest"; }

  explicit SubscribeChainsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SubscribeChainsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SubscribeChainsRequest& from);
  SubscribeChainsRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SubscribeChainsRequest&& from) noexcept
      : SubscribeChainsRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kChainSymbolsFieldNumber = 2,
    kStrategyNameFieldNumber = 1,
  };
  // repeated string chain_symbols = 2;
  int chain_symbols_size() const;
  private:
  int _internal_chain_symbols_size() const;

  public:
  void clear_chain_symbols() ;
  const ::std::string& chain_symbols(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_chain_symbols(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_chain_symbols(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_chain_symbols();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_chain_symbols(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& chain_symbols() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_chain_symbols();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_chain_symbols() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_chain_symbols();

  public:
  // string strategy_name = 1;
  void clear_strategy_name() ;
  const ::std::string& strategy_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_strategy_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_strategy_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_strategy_name();
  void set_allocated_strategy_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_strategy_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_strategy_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_strategy_name();

  public:
  // @@protoc_insertion_point(class_scope:otrader.SubscribeChainsRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 65,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SubscribeChainsRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> chain_symbols_;
    ::google::protobuf::internal::ArenaStringPtr strategy_name_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_marketdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SubscribeChainsRequest_class_data_;
// -------------------------------------------------------------------

class PortfolioSnapshotMsg final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:otrader.PortfolioSnapshotMsg) */ {
 public:
  inline PortfolioSnapshotMsg() : PortfolioSnapshotMsg(nullptr) {}
  ~PortfolioSnapshotMsg() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PortfolioSnapshotMsg* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PortfolioSnapshotMsg));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PortfolioSnapshotMsg(::google::protobuf::internal::ConstantInitialized);

  inline PortfolioSnapshotMsg(const PortfolioSnapshotMsg& from) : PortfolioSnapshotMsg(nullptr, from) {}
  inline PortfolioSnapshotMsg(PortfolioSnapshotMsg&& from) noexcept
      : PortfolioSnapshotMsg(nullptr, ::std::move(from)) {}
  inline PortfolioSnapshotMsg& operator=(const PortfolioSnapshotMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline PortfolioSnapshotMsg& operator=(PortfolioSnapshotMsg&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PortfolioSnapshotMsg& default_instance() {
    return *reinterpret_cast<const PortfolioSnapshotMsg*>(
        &_PortfolioSnapshotMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PortfolioSnapshotMsg& a, PortfolioSnapshotMsg& b) { a.Swap(&b); }
  inline void Swap(PortfolioSnapshotMsg* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PortfolioSnapshotMsg* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PortfolioSnapshotMsg* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PortfolioSnapshotMsg>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PortfolioSnapshotMsg& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PortfolioSnapshotMsg& from) { PortfolioSnapshotMsg::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PortfolioSnapshotMsg* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "otrader.PortfolioSnapshotMsg"; }

  explicit PortfolioSnapshotMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PortfolioSnapshotMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PortfolioSnapshotMsg& from);
  PortfolioSnapshotMsg(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PortfolioSnapshotMsg&& from) noexcept
      : PortfolioSnapshotMsg(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBidFieldNumber = 6,
    kAskFieldNumber = 7,
    kLastFieldNumber = 8,
    kDeltaFieldNumber = 9,
    kGammaFieldNumber = 10,
    kThetaFieldNumber = 11,
    kVegaFieldNumber = 12,
    kIvFieldNumber = 13,
    kPortfolioNameFieldNumber = 1,
    kDatetimeSecondsFieldNumber = 2,
    kUnderlyingBidFieldNumber = 3,
    kUnderlyingAskFieldNumber = 4,
    kUnderlyingLastFieldNumber = 5,
  };
  // repeated double bid = 6;
  int bid_size() const;
  private:
  int _internal_bid_size() const;

  public:
  void clear_bid() ;
  double bid(int index) const;
  void set_bid(int index, double value);
  void add_bid(double value);
  const ::google::protobuf::RepeatedField<double>& bid() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_bid();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_bid() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_bid();

  public:
  // repeated double ask = 7;
  int ask_size() const;
  private:
  int _internal_ask_size() const;

  public:
  void clear_ask() ;
  double ask(int index) const;
  void set_ask(int index, double value);
  void add_ask(double value);
  const ::google::protobuf::RepeatedField<double>& ask() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_ask();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_ask() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_ask();

  public:
  // repeated double last = 8;
  int last_size() const;
  private:
  int _internal_last_size() const;

  public:
  void clear_last() ;
  double last(int index) const;
  void set_last(int index, double value);
  void add_last(double value);
  const ::google::protobuf::RepeatedField<double>& last() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_last();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_last() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_last();

  public:
  // repeated double delta = 9;
  int delta_size() const;
  private:
  int _internal_delta_size() const;

  public:
  void clear_delta() ;
  double delta(int index) const;
  void set_delta(int index, double value);
  void add_delta(double value);
  const ::google::protobuf::RepeatedField<double>& delta() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_delta();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_delta() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_delta();

  public:
  // repeated double gamma = 10;
  int gamma_size() const;
  private:
  int _internal_gamma_size() const;

  public:
  void clear_gamma() ;
  double gamma(int index) const;
  void set_gamma(int index, double value);
  void add_gamma(double value);
  const ::google::protobuf::RepeatedField<double>& gamma() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_gamma();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_gamma() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_gamma();

  public:
  // repeated double theta = 11;
  int theta_size() const;
  private:
  int _internal_theta_size() const;

  public:
  void clear_theta() ;
  double theta(int index) const;
  void set_theta(int index, double value);
  void add_theta(double value);
  const ::google::protobuf::RepeatedField<double>& theta() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_theta();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_theta() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_theta();

  public:
  // repeated double vega = 12;
  int vega_size() const;
  private:
  int _internal_vega_size() const;

  public:
  void clear_vega() ;
  double vega(int index) const;
  void set_vega(int index, double value);
  void add_vega(double value);
  const ::google::protobuf::RepeatedField<double>& vega() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_vega();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_vega() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_vega();

  public:
  // repeated double iv = 13;
  int iv_size() const;
  private:
  int _internal_iv_size() const;

  public:
  void clear_iv() ;
  double iv(int index) const;
  void set_iv(int index, double value);
  void add_iv(double value);
  const ::google::protobuf::RepeatedField<double>& iv() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_iv();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_iv() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_iv();

  public:
  // string portfolio_name = 1;
  void clear_portfolio_name() ;
  const ::std::string& portfolio_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_portfolio_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_portfolio_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_portfolio_name();
  void set_allocated_portfolio_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_portfolio_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_portfolio_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_portfolio_name();

  public:
  // int64 datetime_seconds = 2;
  void clear_datetime_seconds() ;
  ::int64_t datetime_seconds() const;
  void set_datetime_seconds(::int64_t value);

  private:
  ::int64_t _internal_datetime_seconds() const;
  void _internal_set_datetime_seconds(::int64_t value);

  public:
  // double underlying_bid = 3;
  void clear_underlying_bid() ;
  double underlying_bid() const;
  void set_underlying_bid(double value);

  private:
  double _internal_underlying_bid() const;
  void _internal_set_underlying_bid(double value);

  public:
  // double underlying_ask = 4;
  void clear_underlying_ask() ;
  double underlying_ask() const;
  void set_underlying_ask(double value);

  private:
  double _internal_underlying_ask() const;
  void _internal_set_underlying_ask(double value);

  public:
  // double underlying_last = 5;
  void clear_underlying_last() ;
  double underlying_last() const;
  void set_underlying_last(double value);

  private:
  double _internal_underlying_last() const;
  void _internal_set_underlying_last(double value);

  public:
  // @@protoc_insertion_point(class_scope:otrader.PortfolioSnapshotMsg)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 13,
                                   0, 59,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PortfolioSnapshotMsg& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<double> bid_;
    ::google::protobuf::RepeatedField<double> ask_;
    ::google::protobuf::RepeatedField<double> last_;
    ::google::protobuf::RepeatedField<double> delta_;
    ::google::protobuf::RepeatedField<double> gamma_;
    ::google::protobuf::RepeatedField<double> theta_;
    ::google::protobuf::RepeatedField<double> vega_;
    ::google::protobuf::RepeatedField<double> iv_;
    ::google::protobuf::internal::ArenaStringPtr portfolio_name_;
    ::int64_t datetime_seconds_;
    double underlying_bid_;
    double underlying_ask_;
    double underlying_last_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_marketdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PortfolioSnapshotMsg_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SubscribeChainsRequest

// string strategy_name = 1;
inline void SubscribeChainsRequest::clear_strategy_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.strategy_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& SubscribeChainsRequest::strategy_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:otrader.SubscribeChainsRequest.strategy_name)
  return _internal_strategy_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SubscribeChainsRequest::set_strategy_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.strategy_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:otrader.SubscribeChainsRequest.strategy_name)
}
inline ::std::string* PROTOBUF_NONNULL SubscribeChainsRequest::mutable_strategy_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_strategy_name();
  // @@protoc_insertion_point(field_mutable:otrader.SubscribeChainsRequest.strategy_name)
  return _s;
}
inline const ::std::string& SubscribeChainsRequest::_internal_strategy_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.strategy_name_.Get();
}
inline void SubscribeChainsRequest::_internal_set_strategy_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.strategy_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SubscribeChainsRequest::_internal_mutable_strategy_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.strategy_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SubscribeChainsRequest::release_strategy_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:otrader.SubscribeChainsRequest.strategy_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.strategy_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.strategy_name_.Set("", GetArena());
  }
  return released;
}
inline void SubscribeChainsRequest::set_allocated_strategy_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.strategy_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.strategy_name_.IsDefault()) {
    _impl_.strategy_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:otrader.SubscribeChainsRequest.strategy_name)
}

// repeated string chain_symbols = 2;
inline int SubscribeChainsRequest::_internal_chain_symbols_size() const {
  return _internal_chain_symbols().size();
}
inline int SubscribeChainsRequest::chain_symbols_size() const {
  return _internal_chain_symbols_size();
}
inline void SubscribeChainsRequest::clear_chain_symbols() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chain_symbols_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL SubscribeChainsRequest::add_chain_symbols()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_chain_symbols()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:otrader.SubscribeChainsRequest.chain_symbols)
  return _s;
}
inline const ::std::string& SubscribeChainsRequest::chain_symbols(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:otrader.SubscribeChainsRequest.chain_symbols)
  return _internal_chain_symbols().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL SubscribeChainsRequest::mutable_chain_symbols(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:otrader.SubscribeChainsRequest.chain_symbols)
  return _internal_mutable_chain_symbols()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void SubscribeChainsRequest::set_chain_symbols(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_chain_symbols()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:otrader.SubscribeChainsRequest.chain_symbols)
}
template <typename Arg_, typename... Args_>
inline void SubscribeChainsRequest::add_chain_symbols(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_chain_symbols(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:otrader.SubscribeChainsRequest.chain_symbols)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& SubscribeChainsRequest::chain_symbols()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:otrader.SubscribeChainsRequest.chain_symbols)
  return _internal_chain_symbols();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
SubscribeChainsRequest::mutable_chain_symbols() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:otrader.SubscribeChainsRequest.chain_symbols)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_chain_symbols();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
SubscribeChainsRequest::_internal_chain_symbols() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.chain_symbols_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
SubscribeChainsRequest::_internal_mutable_chain_symbols() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.chain_symbols_;
}

// -------------------------------------------------------------------

// UnsubscribeChainsRequest

// string strategy_name = 1;
inline void UnsubscribeChainsRequest::clear_strategy_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.strategy_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& UnsubscribeChainsRequest::strategy_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:otrader.UnsubscribeChainsRequest.strategy_name)
  return _internal_strategy_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void UnsubscribeChainsRequest::set_strategy_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.strategy_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:otrader.UnsubscribeChainsRequest.strategy_name)
}
inline ::std::string* PROTOBUF_NONNULL UnsubscribeChainsRequest::mutable_strategy_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_strategy_name();
  // @@protoc_insertion_point(field_mutable:otrader.UnsubscribeChainsRequest.strategy_name)
  return _s;
}
inline const ::std::string& UnsubscribeChainsRequest::_internal_strategy_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.strategy_name_.Get();
}
inline void UnsubscribeChainsRequest::_internal_set_strategy_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.strategy_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL UnsubscribeChainsRequest::_internal_mutable_strategy_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.strategy_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE UnsubscribeChainsRequest::release_strategy_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:otrader.UnsubscribeChainsRequest.strategy_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.strategy_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.strategy_name_.Set("", GetArena());
  }
  return released;
}
inline void UnsubscribeChainsRequest::set_allocated_strategy_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.strategy_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.strategy_name_.IsDefault()) {
    _impl_.strategy_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:otrader.UnsubscribeChainsRequest.strategy_name)
}

// -------------------------------------------------------------------

// PortfolioSnapshotMsg

// string portfolio_name = 1;
inline void PortfolioSnapshotMsg::clear_portfolio_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.portfolio_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline const ::std::string& PortfolioSnapshotMsg::portfolio_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:otrader.PortfolioSnapshotMsg.portfolio_name)
  return _internal_portfolio_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PortfolioSnapshotMsg::set_portfolio_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  _impl_.portfolio_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:otrader.PortfolioSnapshotMsg.portfolio_name)
}
inline ::std::string* PROTOBUF_NONNULL PortfolioSnapshotMsg::mutable_portfolio_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  ::std::string* _s = _internal_mutable_portfolio_name();
  // @@protoc_insertion_point(field_mutable:otrader.PortfolioSnapshotMsg.portfolio_name)
  return _s;
}
inline const ::std::string& PortfolioSnapshotMsg::_internal_portfolio_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.portfolio_name_.Get();
}
inline void PortfolioSnapshotMsg::_internal_set_portfolio_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.portfolio_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PortfolioSnapshotMsg::_internal_mutable_portfolio_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.portfolio_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PortfolioSnapshotMsg::release_portfolio_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:otrader.PortfolioSnapshotMsg.portfolio_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000100U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000100U);
  auto* released = _impl_.portfolio_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.portfolio_name_.Set("", GetArena());
  }
  return released;
}
inline void PortfolioSnapshotMsg::set_allocated_portfolio_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000100U);
  }
  _impl_.portfolio_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.portfolio_name_.IsDefault()) {
    _impl_.portfolio_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:otrader.PortfolioSnapshotMsg.portfolio_name)
}

// int64 datetime_seconds = 2;
inline void PortfolioSnapshotMsg::clear_datetime_seconds() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.datetime_seconds_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::int64_t PortfolioSnapshotMsg::datetime_seconds() const {
  // @@protoc_insertion_point(field_get:otrader.PortfolioSnapshotMsg.datetime_seconds)
  return _internal_datetime_seconds();
}
inline void PortfolioSnapshotMsg::set_datetime_seconds(::int64_t value) {
  _internal_set_datetime_seconds(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:otrader.PortfolioSnapshotMsg.datetime_seconds)
}
inline ::int64_t PortfolioSnapshotMsg::_internal_datetime_seconds() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.datetime_seconds_;
}
inline void PortfolioSnapshotMsg::_internal_set_datetime_seconds(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.datetime_seconds_ = value;
}

// double underlying_bid = 3;
inline void PortfolioSnapshotMsg::clear_underlying_bid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.underlying_bid_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000400U);
}
inline double PortfolioSnapshotMsg::underlying_bid() const {
  // @@protoc_insertion_point(field_get:otrader.PortfolioSnapshotMsg.underlying_bid)
  return _internal_underlying_bid();
}
inline void PortfolioSnapshotMsg::set_underlying_bid(double value) {
  _internal_set_underlying_bid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_set:otrader.PortfolioSnapshotMsg.underlying_bid)
}
inline double PortfolioSnapshotMsg::_internal_underlying_bid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.underlying_bid_;
}
inline void PortfolioSnapshotMsg::_internal_set_underlying_bid(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.underlying_bid_ = value;
}

// double underlying_ask = 4;
inline void PortfolioSnapshotMsg::clear_underlying_ask() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.underlying_ask_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000800U);
}
inline double PortfolioSnapshotMsg::underlying_ask() const {
  // @@protoc_insertion_point(field_get:otrader.PortfolioSnapshotMsg.underlying_ask)
  return _internal_underlying_ask();
}
inline void PortfolioSnapshotMsg::set_underlying_ask(double value) {
  _internal_set_underlying_ask(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_set:otrader.PortfolioSnapshotMsg.underlying_ask)
}
inline double PortfolioSnapshotMsg::_internal_underlying_ask() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.underlying_ask_;
}
inline void PortfolioSnapshotMsg::_internal_set_underlying_ask(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.underlying_ask_ = value;
}

// double underlying_last = 5;
inline void PortfolioSnapshotMsg::clear_underlying_last() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.underlying_last_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00001000U);
}
inline double PortfolioSnapshotMsg::underlying_last() const {
  // @@protoc_insertion_point(field_get:otrader.PortfolioSnapshotMsg.underlying_last)
  return _internal_underlying_last();
}
inline void PortfolioSnapshotMsg::set_underlying_last(double value) {
  _internal_set_underlying_last(value);
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  // @@protoc_insertion_point(field_set:otrader.PortfolioSnapshotMsg.underlying_last)
}
inline double PortfolioSnapshotMsg::_internal_underlying_last() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.underlying_last_;
}
inline void PortfolioSnapshotMsg::_internal_set_underlying_last(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.underlying_last_ = value;
}

// repeated double bid = 6;
inline int PortfolioSnapshotMsg::_internal_bid_size() const {
  return _internal_bid().size();
}
inline int PortfolioSnapshotMsg::bid_size() const {
  return _internal_bid_size();
}
inline void PortfolioSnapshotMsg::clear_bid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bid_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double PortfolioSnapshotMsg::bid(int index) const {
  // @@protoc_insertion_point(field_get:otrader.PortfolioSnapshotMsg.bid)
  return _internal_bid().Get(index);
}
inline void PortfolioSnapshotMsg::set_bid(int index, double value) {
  _internal_mutable_bid()->Set(index, value);
  // @@protoc_insertion_point(field_set:otrader.PortfolioSnapshotMsg.bid)
}
inline void PortfolioSnapshotMsg::add_bid(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_bid()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:otrader.PortfolioSnapshotMsg.bid)
}
inline const ::google::protobuf::RepeatedField<double>& PortfolioSnapshotMsg::bid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:otrader.PortfolioSnapshotMsg.bid)
  return _internal_bid();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL PortfolioSnapshotMsg::mutable_bid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:otrader.PortfolioSnapshotMsg.bid)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_bid();
}
inline const ::google::protobuf::RepeatedField<double>&
PortfolioSnapshotMsg::_internal_bid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bid_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
PortfolioSnapshotMsg::_internal_mutable_bid() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.bid_;
}

// repeated double ask = 7;
inline int PortfolioSnapshotMsg::_internal_ask_size() const {
  return _internal_ask().size();
}
inline int PortfolioSnapshotMsg::ask_size() const {
  return _internal_ask_size();
}
inline void PortfolioSnapshotMsg::clear_ask() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ask_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double PortfolioSnapshotMsg::ask(int index) const {
  // @@protoc_insertion_point(field_get:otrader.PortfolioSnapshotMsg.ask)
  return _internal_ask().Get(index);
}
inline void PortfolioSnapshotMsg::set_ask(int index, double value) {
  _internal_mutable_ask()->Set(index, value);
  // @@protoc_insertion_point(field_set:otrader.PortfolioSnapshotMsg.ask)
}
inline void PortfolioSnapshotMsg::add_ask(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_ask()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:otrader.PortfolioSnapshotMsg.ask)
}
inline const ::google::protobuf::RepeatedField<double>& PortfolioSnapshotMsg::ask() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:otrader.PortfolioSnapshotMsg.ask)
  return _internal_ask();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL PortfolioSnapshotMsg::mutable_ask()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:otrader.PortfolioSnapshotMsg.ask)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_ask();
}
inline const ::google::protobuf::RepeatedField<double>&
PortfolioSnapshotMsg::_internal_ask() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ask_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
PortfolioSnapshotMsg::_internal_mutable_ask() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.ask_;
}

// repeated double last = 8;
inline int PortfolioSnapshotMsg::_internal_last_size() const {
  return _internal_last().size();
}
inline int PortfolioSnapshotMsg::last_size() const {
  return _internal_last_size();
}
inline void PortfolioSnapshotMsg::clear_last() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.last_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double PortfolioSnapshotMsg::last(int index) const {
  // @@protoc_insertion_point(field_get:otrader.PortfolioSnapshotMsg.last)
  return _internal_last().Get(index);
}
inline void PortfolioSnapshotMsg::set_last(int index, double value) {
  _internal_mutable_last()->Set(index, value);
  // @@protoc_insertion_point(field_set:otrader.PortfolioSnapshotMsg.last)
}
inline void PortfolioSnapshotMsg::add_last(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_last()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_add:otrader.PortfolioSnapshotMsg.last)
}
inline const ::google::protobuf::RepeatedField<double>& PortfolioSnapshotMsg::last() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:otrader.PortfolioSnapshotMsg.last)
  return _internal_last();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL PortfolioSnapshotMsg::mutable_last()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_list:otrader.PortfolioSnapshotMsg.last)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_last();
}
inline const ::google::protobuf::RepeatedField<double>&
PortfolioSnapshotMsg::_internal_last() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.last_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
PortfolioSnapshotMsg::_internal_mutable_last() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.last_;
}

// repeated double delta = 9;
inline int PortfolioSnapshotMsg::_internal_delta_size() const {
  return _internal_delta().size();
}
inline int PortfolioSnapshotMsg::delta_size() const {
  return _internal_delta_size();
}
inline void PortfolioSnapshotMsg::clear_delta() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.delta_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000008U);
}
inline double PortfolioSnapshotMsg::delta(int index) const {
  // @@protoc_insertion_point(field_get:otrader.PortfolioSnapshotMsg.delta)
  return _internal_delta().Get(index);
}
inline void PortfolioSnapshotMsg::set_delta(int index, double value) {
  _internal_mutable_delta()->Set(index, value);
  // @@protoc_insertion_point(field_set:otrader.PortfolioSnapshotMsg.delta)
}
inline void PortfolioSnapshotMsg::add_delta(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_delta()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_add:otrader.PortfolioSnapshotMsg.delta)
}
inline const ::google::protobuf::RepeatedField<double>& PortfolioSnapshotMsg::delta() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:otrader.PortfolioSnapshotMsg.delta)
  return _internal_delta();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL PortfolioSnapshotMsg::mutable_delta()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_mutable_list:otrader.PortfolioSnapshotMsg.delta)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_delta();
}
inline const ::google::protobuf::RepeatedField<double>&
PortfolioSnapshotMsg::_internal_delta() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.delta_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
PortfolioSnapshotMsg::_internal_mutable_delta() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.delta_;
}

// repeated double gamma = 10;
inline int PortfolioSnapshotMsg::_internal_gamma_size() const {
  return _internal_gamma().size();
}
inline int PortfolioSnapshotMsg::gamma_size() const {
  return _internal_gamma_size();
}
inline void PortfolioSnapshotMsg::clear_gamma() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gamma_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000010U);
}
inline double PortfolioSnapshotMsg::gamma(int index) const {
  // @@protoc_insertion_point(field_get:otrader.PortfolioSnapshotMsg.gamma)
  return _internal_gamma().Get(index);
}
inline void PortfolioSnapshotMsg::set_gamma(int index, double value) {
  _internal_mutable_gamma()->Set(index, value);
  // @@protoc_insertion_point(field_set:otrader.PortfolioSnapshotMsg.gamma)
}
inline void PortfolioSnapshotMsg::add_gamma(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_gamma()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_add:otrader.PortfolioSnapshotMsg.gamma)
}
inline const ::google::protobuf::RepeatedField<double>& PortfolioSnapshotMsg::gamma() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:otrader.PortfolioSnapshotMsg.gamma)
  return _internal_gamma();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL PortfolioSnapshotMsg::mutable_gamma()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_mutable_list:otrader.PortfolioSnapshotMsg.gamma)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_gamma();
}
inline const ::google::protobuf::RepeatedField<double>&
PortfolioSnapshotMsg::_internal_gamma() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gamma_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
PortfolioSnapshotMsg::_internal_mutable_gamma() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.gamma_;
}

// repeated double theta = 11;
inline int PortfolioSnapshotMsg::_internal_theta_size() const {
  return _internal_theta().size();
}
inline int PortfolioSnapshotMsg::theta_size() const {
  return _internal_theta_size();
}
inline void PortfolioSnapshotMsg::clear_theta() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.theta_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000020U);
}
inline double PortfolioSnapshotMsg::theta(int index) const {
  // @@protoc_insertion_point(field_get:otrader.PortfolioSnapshotMsg.theta)
  return _internal_theta().Get(index);
}
inline void PortfolioSnapshotMsg::set_theta(int index, double value) {
  _internal_mutable_theta()->Set(index, value);
  // @@protoc_insertion_point(field_set:otrader.PortfolioSnapshotMsg.theta)
}
inline void PortfolioSnapshotMsg::add_theta(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_theta()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_add:otrader.PortfolioSnapshotMsg.theta)
}
inline const ::google::protobuf::RepeatedField<double>& PortfolioSnapshotMsg::theta() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:otrader.PortfolioSnapshotMsg.theta)
  return _internal_theta();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL PortfolioSnapshotMsg::mutable_theta()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_mutable_list:otrader.PortfolioSnapshotMsg.theta)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_theta();
}
inline const ::google::protobuf::RepeatedField<double>&
PortfolioSnapshotMsg::_internal_theta() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.theta_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
PortfolioSnapshotMsg::_internal_mutable_theta() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.theta_;
}

// repeated double vega = 12;
inline int PortfolioSnapshotMsg::_internal_vega_size() const {
  return _internal_vega().size();
}
inline int PortfolioSnapshotMsg::vega_size() const {
  return _internal_vega_size();
}
inline void PortfolioSnapshotMsg::clear_vega() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vega_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000040U);
}
inline double PortfolioSnapshotMsg::vega(int index) const {
  // @@protoc_insertion_point(field_get:otrader.PortfolioSnapshotMsg.vega)
  return _internal_vega().Get(index);
}
inline void PortfolioSnapshotMsg::set_vega(int index, double value) {
  _internal_mutable_vega()->Set(index, value);
  // @@protoc_insertion_point(field_set:otrader.PortfolioSnapshotMsg.vega)
}
inline void PortfolioSnapshotMsg::add_vega(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_vega()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_add:otrader.PortfolioSnapshotMsg.vega)
}
inline const ::google::protobuf::RepeatedField<double>& PortfolioSnapshotMsg::vega() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:otrader.PortfolioSnapshotMsg.vega)
  return _internal_vega();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL PortfolioSnapshotMsg::mutable_vega()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_mutable_list:otrader.PortfolioSnapshotMsg.vega)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_vega();
}
inline const ::google::protobuf::RepeatedField<double>&
PortfolioSnapshotMsg::_internal_vega() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vega_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
PortfolioSnapshotMsg::_internal_mutable_vega() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.vega_;
}

// repeated double iv = 13;
inline int PortfolioSnapshotMsg::_internal_iv_size() const {
  return _internal_iv().size();
}
inline int PortfolioSnapshotMsg::iv_size() const {
  return _internal_iv_size();
}
inline void PortfolioSnapshotMsg::clear_iv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iv_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000080U);
}
inline double PortfolioSnapshotMsg::iv(int index) const {
  // @@protoc_insertion_point(field_get:otrader.PortfolioSnapshotMsg.iv)
  return _internal_iv().Get(index);
}
inline void PortfolioSnapshotMsg::set_iv(int index, double value) {
  _internal_mutable_iv()->Set(index, value);
  // @@protoc_insertion_point(field_set:otrader.PortfolioSnapshotMsg.iv)
}
inline void PortfolioSnapshotMsg::add_iv(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_iv()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_add:otrader.PortfolioSnapshotMsg.iv)
}
inline const ::google::protobuf::RepeatedField<double>& PortfolioSnapshotMsg::iv() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:otrader.PortfolioSnapshotMsg.iv)
  return _internal_iv();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL PortfolioSnapshotMsg::mutable_iv()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_mutable_list:otrader.PortfolioSnapshotMsg.iv)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_iv();
}
inline const ::google::protobuf::RepeatedField<double>&
PortfolioSnapshotMsg::_internal_iv() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.iv_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
PortfolioSnapshotMsg::_internal_mutable_iv() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.iv_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace otrader


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // marketdata_2eproto_2epb_2eh
