// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: marketdata.proto
// Protobuf C++ Version: 6.33.4

#include "marketdata.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace otrader {

inline constexpr UnsubscribeChainsRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        strategy_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR UnsubscribeChainsRequest::UnsubscribeChainsRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(UnsubscribeChainsRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UnsubscribeChainsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UnsubscribeChainsRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UnsubscribeChainsRequestDefaultTypeInternal() {}
  union {
    UnsubscribeChainsRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UnsubscribeChainsRequestDefaultTypeInternal _UnsubscribeChainsRequest_default_instance_;

inline constexpr SubscribeChainsRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        chain_symbols_{},
        strategy_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR SubscribeChainsRequest::SubscribeChainsRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SubscribeChainsRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SubscribeChainsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SubscribeChainsRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SubscribeChainsRequestDefaultTypeInternal() {}
  union {
    SubscribeChainsRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SubscribeChainsRequestDefaultTypeInternal _SubscribeChainsRequest_default_instance_;

inline constexpr PortfolioSnapshotMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        bid_{},
        ask_{},
        last_{},
        delta_{},
        gamma_{},
        theta_{},
        vega_{},
        iv_{},
        portfolio_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        datetime_seconds_{::int64_t{0}},
        underlying_bid_{0},
        underlying_ask_{0},
        underlying_last_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PortfolioSnapshotMsg::PortfolioSnapshotMsg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PortfolioSnapshotMsg_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PortfolioSnapshotMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PortfolioSnapshotMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PortfolioSnapshotMsgDefaultTypeInternal() {}
  union {
    PortfolioSnapshotMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PortfolioSnapshotMsgDefaultTypeInternal _PortfolioSnapshotMsg_default_instance_;
}  // namespace otrader
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_marketdata_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_marketdata_2eproto = nullptr;
const ::uint32_t
    TableStruct_marketdata_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::otrader::SubscribeChainsRequest, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::otrader::SubscribeChainsRequest, _impl_.strategy_name_),
        PROTOBUF_FIELD_OFFSET(::otrader::SubscribeChainsRequest, _impl_.chain_symbols_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::otrader::UnsubscribeChainsRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::otrader::UnsubscribeChainsRequest, _impl_.strategy_name_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::otrader::PortfolioSnapshotMsg, _impl_._has_bits_),
        16, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::otrader::PortfolioSnapshotMsg, _impl_.portfolio_name_),
        PROTOBUF_FIELD_OFFSET(::otrader::PortfolioSnapshotMsg, _impl_.datetime_seconds_),
        PROTOBUF_FIELD_OFFSET(::otrader::PortfolioSnapshotMsg, _impl_.underlying_bid_),
        PROTOBUF_FIELD_OFFSET(::otrader::PortfolioSnapshotMsg, _impl_.underlying_ask_),
        PROTOBUF_FIELD_OFFSET(::otrader::PortfolioSnapshotMsg, _impl_.underlying_last_),
        PROTOBUF_FIELD_OFFSET(::otrader::PortfolioSnapshotMsg, _impl_.bid_),
        PROTOBUF_FIELD_OFFSET(::otrader::PortfolioSnapshotMsg, _impl_.ask_),
        PROTOBUF_FIELD_OFFSET(::otrader::PortfolioSnapshotMsg, _impl_.last_),
        PROTOBUF_FIELD_OFFSET(::otrader::PortfolioSnapshotMsg, _impl_.delta_),
        PROTOBUF_FIELD_OFFSET(::otrader::PortfolioSnapshotMsg, _impl_.gamma_),
        PROTOBUF_FIELD_OFFSET(::otrader::PortfolioSnapshotMsg, _impl_.theta_),
        PROTOBUF_FIELD_OFFSET(::otrader::PortfolioSnapshotMsg, _impl_.vega_),
        PROTOBUF_FIELD_OFFSET(::otrader::PortfolioSnapshotMsg, _impl_.iv_),
        8,
        9,
        10,
        11,
        12,
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::otrader::SubscribeChainsRequest)},
        {7, sizeof(::otrader::UnsubscribeChainsRequest)},
        {12, sizeof(::otrader::PortfolioSnapshotMsg)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::otrader::_SubscribeChainsRequest_default_instance_._instance,
    &::otrader::_UnsubscribeChainsRequest_default_instance_._instance,
    &::otrader::_PortfolioSnapshotMsg_default_instance_._instance,
};
const char descriptor_table_protodef_marketdata_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020marketdata.proto\022\007otrader\032\024otrader_eng"
    "ine.proto\"F\n\026SubscribeChainsRequest\022\025\n\rs"
    "trategy_name\030\001 \001(\t\022\025\n\rchain_symbols\030\002 \003("
    "\t\"1\n\030UnsubscribeChainsRequest\022\025\n\rstrateg"
    "y_name\030\001 \001(\t\"\200\002\n\024PortfolioSnapshotMsg\022\026\n"
    "\016portfolio_name\030\001 \001(\t\022\030\n\020datetime_second"
    "s\030\002 \001(\003\022\026\n\016underlying_bid\030\003 \001(\001\022\026\n\016under"
    "lying_ask\030\004 \001(\001\022\027\n\017underlying_last\030\005 \001(\001"
    "\022\013\n\003bid\030\006 \003(\001\022\013\n\003ask\030\007 \003(\001\022\014\n\004last\030\010 \003(\001"
    "\022\r\n\005delta\030\t \003(\001\022\r\n\005gamma\030\n \003(\001\022\r\n\005theta\030"
    "\013 \003(\001\022\014\n\004vega\030\014 \003(\001\022\n\n\002iv\030\r \003(\0012\264\002\n\021Mark"
    "etDataService\022\'\n\005Start\022\016.otrader.Empty\032\016"
    ".otrader.Empty\022&\n\004Stop\022\016.otrader.Empty\032\016"
    ".otrader.Empty\022B\n\017SubscribeChains\022\037.otra"
    "der.SubscribeChainsRequest\032\016.otrader.Emp"
    "ty\022F\n\021UnsubscribeChains\022!.otrader.Unsubs"
    "cribeChainsRequest\032\016.otrader.Empty\022B\n\017St"
    "reamSnapshots\022\016.otrader.Empty\032\035.otrader."
    "PortfolioSnapshotMsg0\001b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_marketdata_2eproto_deps[1] = {
        &::descriptor_table_otrader_5fengine_2eproto,
};
static ::absl::once_flag descriptor_table_marketdata_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_marketdata_2eproto = {
    false,
    false,
    750,
    descriptor_table_protodef_marketdata_2eproto,
    "marketdata.proto",
    &descriptor_table_marketdata_2eproto_once,
    descriptor_table_marketdata_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_marketdata_2eproto::offsets,
    file_level_enum_descriptors_marketdata_2eproto,
    file_level_service_descriptors_marketdata_2eproto,
};
namespace otrader {
// ===================================================================

class SubscribeChainsRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SubscribeChainsRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SubscribeChainsRequest, _impl_._has_bits_);
};

SubscribeChainsRequest::SubscribeChainsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SubscribeChainsRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:otrader.SubscribeChainsRequest)
}
PROTOBUF_NDEBUG_INLINE SubscribeChainsRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::otrader::SubscribeChainsRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        chain_symbols_{visibility, arena, from.chain_symbols_},
        strategy_name_(arena, from.strategy_name_) {}

SubscribeChainsRequest::SubscribeChainsRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SubscribeChainsRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SubscribeChainsRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SubscribeChainsRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:otrader.SubscribeChainsRequest)
}
PROTOBUF_NDEBUG_INLINE SubscribeChainsRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        chain_symbols_{visibility, arena},
        strategy_name_(arena) {}

inline void SubscribeChainsRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SubscribeChainsRequest::~SubscribeChainsRequest() {
  // @@protoc_insertion_point(destructor:otrader.SubscribeChainsRequest)
  SharedDtor(*this);
}
inline void SubscribeChainsRequest::SharedDtor(MessageLite& self) {
  SubscribeChainsRequest& this_ = static_cast<SubscribeChainsRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.strategy_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SubscribeChainsRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SubscribeChainsRequest(arena);
}
constexpr auto SubscribeChainsRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SubscribeChainsRequest, _impl_.chain_symbols_) +
          decltype(SubscribeChainsRequest::_impl_.chain_symbols_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(SubscribeChainsRequest), alignof(SubscribeChainsRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SubscribeChainsRequest::PlacementNew_,
                                 sizeof(SubscribeChainsRequest),
                                 alignof(SubscribeChainsRequest));
  }
}
constexpr auto SubscribeChainsRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SubscribeChainsRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SubscribeChainsRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SubscribeChainsRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SubscribeChainsRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SubscribeChainsRequest>(), &SubscribeChainsRequest::ByteSizeLong,
              &SubscribeChainsRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SubscribeChainsRequest, _impl_._cached_size_),
          false,
      },
      &SubscribeChainsRequest::kDescriptorMethods,
      &descriptor_table_marketdata_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SubscribeChainsRequest_class_data_ =
        SubscribeChainsRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SubscribeChainsRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SubscribeChainsRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SubscribeChainsRequest_class_data_.tc_table);
  return SubscribeChainsRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 65, 2>
SubscribeChainsRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SubscribeChainsRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SubscribeChainsRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::otrader::SubscribeChainsRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string chain_symbols = 2;
    {::_pbi::TcParser::FastUR1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(SubscribeChainsRequest, _impl_.chain_symbols_)}},
    // string strategy_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 1, 0,
      PROTOBUF_FIELD_OFFSET(SubscribeChainsRequest, _impl_.strategy_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string strategy_name = 1;
    {PROTOBUF_FIELD_OFFSET(SubscribeChainsRequest, _impl_.strategy_name_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated string chain_symbols = 2;
    {PROTOBUF_FIELD_OFFSET(SubscribeChainsRequest, _impl_.chain_symbols_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\36\15\15\0\0\0\0\0"
    "otrader.SubscribeChainsRequest"
    "strategy_name"
    "chain_symbols"
  }},
};
PROTOBUF_NOINLINE void SubscribeChainsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:otrader.SubscribeChainsRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.chain_symbols_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.strategy_name_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SubscribeChainsRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SubscribeChainsRequest& this_ = static_cast<const SubscribeChainsRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SubscribeChainsRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SubscribeChainsRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:otrader.SubscribeChainsRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string strategy_name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_strategy_name().empty()) {
      const ::std::string& _s = this_._internal_strategy_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "otrader.SubscribeChainsRequest.strategy_name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // repeated string chain_symbols = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_chain_symbols_size(); i < n; ++i) {
      const auto& s = this_._internal_chain_symbols().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "otrader.SubscribeChainsRequest.chain_symbols");
      target = stream->WriteString(2, s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:otrader.SubscribeChainsRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SubscribeChainsRequest::ByteSizeLong(const MessageLite& base) {
  const SubscribeChainsRequest& this_ = static_cast<const SubscribeChainsRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SubscribeChainsRequest::ByteSizeLong() const {
  const SubscribeChainsRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:otrader.SubscribeChainsRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated string chain_symbols = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_chain_symbols().size());
      for (int i = 0, n = this_._internal_chain_symbols().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_chain_symbols().Get(i));
      }
    }
    // string strategy_name = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_strategy_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_strategy_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SubscribeChainsRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SubscribeChainsRequest*>(&to_msg);
  auto& from = static_cast<const SubscribeChainsRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:otrader.SubscribeChainsRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_chain_symbols()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_chain_symbols());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_strategy_name().empty()) {
        _this->_internal_set_strategy_name(from._internal_strategy_name());
      } else {
        if (_this->_impl_.strategy_name_.IsDefault()) {
          _this->_internal_set_strategy_name("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SubscribeChainsRequest::CopyFrom(const SubscribeChainsRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:otrader.SubscribeChainsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SubscribeChainsRequest::InternalSwap(SubscribeChainsRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.chain_symbols_.InternalSwap(&other->_impl_.chain_symbols_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.strategy_name_, &other->_impl_.strategy_name_, arena);
}

::google::protobuf::Metadata SubscribeChainsRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UnsubscribeChainsRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<UnsubscribeChainsRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(UnsubscribeChainsRequest, _impl_._has_bits_);
};

UnsubscribeChainsRequest::UnsubscribeChainsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UnsubscribeChainsRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:otrader.UnsubscribeChainsRequest)
}
PROTOBUF_NDEBUG_INLINE UnsubscribeChainsRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::otrader::UnsubscribeChainsRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        strategy_name_(arena, from.strategy_name_) {}

UnsubscribeChainsRequest::UnsubscribeChainsRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const UnsubscribeChainsRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UnsubscribeChainsRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UnsubscribeChainsRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:otrader.UnsubscribeChainsRequest)
}
PROTOBUF_NDEBUG_INLINE UnsubscribeChainsRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        strategy_name_(arena) {}

inline void UnsubscribeChainsRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UnsubscribeChainsRequest::~UnsubscribeChainsRequest() {
  // @@protoc_insertion_point(destructor:otrader.UnsubscribeChainsRequest)
  SharedDtor(*this);
}
inline void UnsubscribeChainsRequest::SharedDtor(MessageLite& self) {
  UnsubscribeChainsRequest& this_ = static_cast<UnsubscribeChainsRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.strategy_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL UnsubscribeChainsRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) UnsubscribeChainsRequest(arena);
}
constexpr auto UnsubscribeChainsRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UnsubscribeChainsRequest),
                                            alignof(UnsubscribeChainsRequest));
}
constexpr auto UnsubscribeChainsRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_UnsubscribeChainsRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &UnsubscribeChainsRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<UnsubscribeChainsRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &UnsubscribeChainsRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<UnsubscribeChainsRequest>(), &UnsubscribeChainsRequest::ByteSizeLong,
              &UnsubscribeChainsRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(UnsubscribeChainsRequest, _impl_._cached_size_),
          false,
      },
      &UnsubscribeChainsRequest::kDescriptorMethods,
      &descriptor_table_marketdata_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull UnsubscribeChainsRequest_class_data_ =
        UnsubscribeChainsRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
UnsubscribeChainsRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&UnsubscribeChainsRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(UnsubscribeChainsRequest_class_data_.tc_table);
  return UnsubscribeChainsRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 54, 2>
UnsubscribeChainsRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(UnsubscribeChainsRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    UnsubscribeChainsRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::otrader::UnsubscribeChainsRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string strategy_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(UnsubscribeChainsRequest, _impl_.strategy_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string strategy_name = 1;
    {PROTOBUF_FIELD_OFFSET(UnsubscribeChainsRequest, _impl_.strategy_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\40\15\0\0\0\0\0\0"
    "otrader.UnsubscribeChainsRequest"
    "strategy_name"
  }},
};
PROTOBUF_NOINLINE void UnsubscribeChainsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:otrader.UnsubscribeChainsRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.strategy_name_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL UnsubscribeChainsRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const UnsubscribeChainsRequest& this_ = static_cast<const UnsubscribeChainsRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL UnsubscribeChainsRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const UnsubscribeChainsRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:otrader.UnsubscribeChainsRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string strategy_name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_strategy_name().empty()) {
      const ::std::string& _s = this_._internal_strategy_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "otrader.UnsubscribeChainsRequest.strategy_name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:otrader.UnsubscribeChainsRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t UnsubscribeChainsRequest::ByteSizeLong(const MessageLite& base) {
  const UnsubscribeChainsRequest& this_ = static_cast<const UnsubscribeChainsRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t UnsubscribeChainsRequest::ByteSizeLong() const {
  const UnsubscribeChainsRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:otrader.UnsubscribeChainsRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string strategy_name = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_strategy_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_strategy_name());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void UnsubscribeChainsRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<UnsubscribeChainsRequest*>(&to_msg);
  auto& from = static_cast<const UnsubscribeChainsRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:otrader.UnsubscribeChainsRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_strategy_name().empty()) {
      _this->_internal_set_strategy_name(from._internal_strategy_name());
    } else {
      if (_this->_impl_.strategy_name_.IsDefault()) {
        _this->_internal_set_strategy_name("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void UnsubscribeChainsRequest::CopyFrom(const UnsubscribeChainsRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:otrader.UnsubscribeChainsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UnsubscribeChainsRequest::InternalSwap(UnsubscribeChainsRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.strategy_name_, &other->_impl_.strategy_name_, arena);
}

::google::protobuf::Metadata UnsubscribeChainsRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PortfolioSnapshotMsg::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PortfolioSnapshotMsg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_._has_bits_);
};

PortfolioSnapshotMsg::PortfolioSnapshotMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PortfolioSnapshotMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:otrader.PortfolioSnapshotMsg)
}
PROTOBUF_NDEBUG_INLINE PortfolioSnapshotMsg::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::otrader::PortfolioSnapshotMsg& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        bid_{visibility, arena, from.bid_},
        ask_{visibility, arena, from.ask_},
        last_{visibility, arena, from.last_},
        delta_{visibility, arena, from.delta_},
        gamma_{visibility, arena, from.gamma_},
        theta_{visibility, arena, from.theta_},
        vega_{visibility, arena, from.vega_},
        iv_{visibility, arena, from.iv_},
        portfolio_name_(arena, from.portfolio_name_) {}

PortfolioSnapshotMsg::PortfolioSnapshotMsg(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PortfolioSnapshotMsg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PortfolioSnapshotMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PortfolioSnapshotMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, datetime_seconds_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, datetime_seconds_),
           offsetof(Impl_, underlying_last_) -
               offsetof(Impl_, datetime_seconds_) +
               sizeof(Impl_::underlying_last_));

  // @@protoc_insertion_point(copy_constructor:otrader.PortfolioSnapshotMsg)
}
PROTOBUF_NDEBUG_INLINE PortfolioSnapshotMsg::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        bid_{visibility, arena},
        ask_{visibility, arena},
        last_{visibility, arena},
        delta_{visibility, arena},
        gamma_{visibility, arena},
        theta_{visibility, arena},
        vega_{visibility, arena},
        iv_{visibility, arena},
        portfolio_name_(arena) {}

inline void PortfolioSnapshotMsg::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, datetime_seconds_),
           0,
           offsetof(Impl_, underlying_last_) -
               offsetof(Impl_, datetime_seconds_) +
               sizeof(Impl_::underlying_last_));
}
PortfolioSnapshotMsg::~PortfolioSnapshotMsg() {
  // @@protoc_insertion_point(destructor:otrader.PortfolioSnapshotMsg)
  SharedDtor(*this);
}
inline void PortfolioSnapshotMsg::SharedDtor(MessageLite& self) {
  PortfolioSnapshotMsg& this_ = static_cast<PortfolioSnapshotMsg&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.portfolio_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PortfolioSnapshotMsg::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PortfolioSnapshotMsg(arena);
}
constexpr auto PortfolioSnapshotMsg::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.bid_) +
          decltype(PortfolioSnapshotMsg::_impl_.bid_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.ask_) +
          decltype(PortfolioSnapshotMsg::_impl_.ask_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.last_) +
          decltype(PortfolioSnapshotMsg::_impl_.last_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.delta_) +
          decltype(PortfolioSnapshotMsg::_impl_.delta_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.gamma_) +
          decltype(PortfolioSnapshotMsg::_impl_.gamma_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.theta_) +
          decltype(PortfolioSnapshotMsg::_impl_.theta_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.vega_) +
          decltype(PortfolioSnapshotMsg::_impl_.vega_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.iv_) +
          decltype(PortfolioSnapshotMsg::_impl_.iv_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(PortfolioSnapshotMsg), alignof(PortfolioSnapshotMsg), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PortfolioSnapshotMsg::PlacementNew_,
                                 sizeof(PortfolioSnapshotMsg),
                                 alignof(PortfolioSnapshotMsg));
  }
}
constexpr auto PortfolioSnapshotMsg::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PortfolioSnapshotMsg_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PortfolioSnapshotMsg::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PortfolioSnapshotMsg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PortfolioSnapshotMsg::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PortfolioSnapshotMsg>(), &PortfolioSnapshotMsg::ByteSizeLong,
              &PortfolioSnapshotMsg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_._cached_size_),
          false,
      },
      &PortfolioSnapshotMsg::kDescriptorMethods,
      &descriptor_table_marketdata_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PortfolioSnapshotMsg_class_data_ =
        PortfolioSnapshotMsg::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PortfolioSnapshotMsg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PortfolioSnapshotMsg_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PortfolioSnapshotMsg_class_data_.tc_table);
  return PortfolioSnapshotMsg_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 13, 0, 59, 2>
PortfolioSnapshotMsg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_._has_bits_),
    0, // no _extensions_
    13, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294959104,  // skipmap
    offsetof(decltype(_table_), field_entries),
    13,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PortfolioSnapshotMsg_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::otrader::PortfolioSnapshotMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string portfolio_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 8, 0,
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.portfolio_name_)}},
    // int64 datetime_seconds = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PortfolioSnapshotMsg, _impl_.datetime_seconds_), 9>(),
     {16, 9, 0,
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.datetime_seconds_)}},
    // double underlying_bid = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 10, 0,
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.underlying_bid_)}},
    // double underlying_ask = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 11, 0,
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.underlying_ask_)}},
    // double underlying_last = 5;
    {::_pbi::TcParser::FastF64S1,
     {41, 12, 0,
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.underlying_last_)}},
    // repeated double bid = 6;
    {::_pbi::TcParser::FastF64P1,
     {50, 0, 0,
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.bid_)}},
    // repeated double ask = 7;
    {::_pbi::TcParser::FastF64P1,
     {58, 1, 0,
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.ask_)}},
    // repeated double last = 8;
    {::_pbi::TcParser::FastF64P1,
     {66, 2, 0,
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.last_)}},
    // repeated double delta = 9;
    {::_pbi::TcParser::FastF64P1,
     {74, 3, 0,
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.delta_)}},
    // repeated double gamma = 10;
    {::_pbi::TcParser::FastF64P1,
     {82, 4, 0,
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.gamma_)}},
    // repeated double theta = 11;
    {::_pbi::TcParser::FastF64P1,
     {90, 5, 0,
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.theta_)}},
    // repeated double vega = 12;
    {::_pbi::TcParser::FastF64P1,
     {98, 6, 0,
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.vega_)}},
    // repeated double iv = 13;
    {::_pbi::TcParser::FastF64P1,
     {106, 7, 0,
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.iv_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string portfolio_name = 1;
    {PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.portfolio_name_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 datetime_seconds = 2;
    {PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.datetime_seconds_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // double underlying_bid = 3;
    {PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.underlying_bid_), _Internal::kHasBitsOffset + 10, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double underlying_ask = 4;
    {PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.underlying_ask_), _Internal::kHasBitsOffset + 11, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double underlying_last = 5;
    {PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.underlying_last_), _Internal::kHasBitsOffset + 12, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // repeated double bid = 6;
    {PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.bid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated double ask = 7;
    {PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.ask_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated double last = 8;
    {PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.last_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated double delta = 9;
    {PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.delta_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated double gamma = 10;
    {PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.gamma_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated double theta = 11;
    {PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.theta_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated double vega = 12;
    {PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.vega_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated double iv = 13;
    {PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.iv_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
  }},
  // no aux_entries
  {{
    "\34\16\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    "otrader.PortfolioSnapshotMsg"
    "portfolio_name"
  }},
};
PROTOBUF_NOINLINE void PortfolioSnapshotMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:otrader.PortfolioSnapshotMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.bid_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.ask_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _impl_.last_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000008U)) {
      _impl_.delta_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000010U)) {
      _impl_.gamma_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000020U)) {
      _impl_.theta_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000040U)) {
      _impl_.vega_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000080U)) {
      _impl_.iv_.Clear();
    }
  }
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    _impl_.portfolio_name_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00001e00U)) {
    ::memset(&_impl_.datetime_seconds_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.underlying_last_) -
        reinterpret_cast<char*>(&_impl_.datetime_seconds_)) + sizeof(_impl_.underlying_last_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PortfolioSnapshotMsg::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PortfolioSnapshotMsg& this_ = static_cast<const PortfolioSnapshotMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PortfolioSnapshotMsg::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PortfolioSnapshotMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:otrader.PortfolioSnapshotMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string portfolio_name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (!this_._internal_portfolio_name().empty()) {
      const ::std::string& _s = this_._internal_portfolio_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "otrader.PortfolioSnapshotMsg.portfolio_name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int64 datetime_seconds = 2;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    if (this_._internal_datetime_seconds() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_datetime_seconds(), target);
    }
  }

  // double underlying_bid = 3;
  if (CheckHasBit(cached_has_bits, 0x00000400U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_underlying_bid()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          3, this_._internal_underlying_bid(), target);
    }
  }

  // double underlying_ask = 4;
  if (CheckHasBit(cached_has_bits, 0x00000800U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_underlying_ask()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          4, this_._internal_underlying_ask(), target);
    }
  }

  // double underlying_last = 5;
  if (CheckHasBit(cached_has_bits, 0x00001000U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_underlying_last()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          5, this_._internal_underlying_last(), target);
    }
  }

  // repeated double bid = 6;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    if (this_._internal_bid_size() > 0) {
      target = stream->WriteFixedPacked(6, this_._internal_bid(), target);
    }
  }

  // repeated double ask = 7;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    if (this_._internal_ask_size() > 0) {
      target = stream->WriteFixedPacked(7, this_._internal_ask(), target);
    }
  }

  // repeated double last = 8;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
    if (this_._internal_last_size() > 0) {
      target = stream->WriteFixedPacked(8, this_._internal_last(), target);
    }
  }

  // repeated double delta = 9;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000008U)) {
    if (this_._internal_delta_size() > 0) {
      target = stream->WriteFixedPacked(9, this_._internal_delta(), target);
    }
  }

  // repeated double gamma = 10;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000010U)) {
    if (this_._internal_gamma_size() > 0) {
      target = stream->WriteFixedPacked(10, this_._internal_gamma(), target);
    }
  }

  // repeated double theta = 11;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000020U)) {
    if (this_._internal_theta_size() > 0) {
      target = stream->WriteFixedPacked(11, this_._internal_theta(), target);
    }
  }

  // repeated double vega = 12;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000040U)) {
    if (this_._internal_vega_size() > 0) {
      target = stream->WriteFixedPacked(12, this_._internal_vega(), target);
    }
  }

  // repeated double iv = 13;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000080U)) {
    if (this_._internal_iv_size() > 0) {
      target = stream->WriteFixedPacked(13, this_._internal_iv(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:otrader.PortfolioSnapshotMsg)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PortfolioSnapshotMsg::ByteSizeLong(const MessageLite& base) {
  const PortfolioSnapshotMsg& this_ = static_cast<const PortfolioSnapshotMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PortfolioSnapshotMsg::ByteSizeLong() const {
  const PortfolioSnapshotMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:otrader.PortfolioSnapshotMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // repeated double bid = 6;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_bid_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double ask = 7;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_ask_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double last = 8;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_last_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double delta = 9;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000008U)) {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_delta_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double gamma = 10;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000010U)) {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_gamma_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double theta = 11;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000020U)) {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_theta_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double vega = 12;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000040U)) {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_vega_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double iv = 13;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000080U)) {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_iv_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00001f00U)) {
    // string portfolio_name = 1;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (!this_._internal_portfolio_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_portfolio_name());
      }
    }
    // int64 datetime_seconds = 2;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (this_._internal_datetime_seconds() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_datetime_seconds());
      }
    }
    // double underlying_bid = 3;
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_underlying_bid()) != 0) {
        total_size += 9;
      }
    }
    // double underlying_ask = 4;
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_underlying_ask()) != 0) {
        total_size += 9;
      }
    }
    // double underlying_last = 5;
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_underlying_last()) != 0) {
        total_size += 9;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PortfolioSnapshotMsg::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PortfolioSnapshotMsg*>(&to_msg);
  auto& from = static_cast<const PortfolioSnapshotMsg&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:otrader.PortfolioSnapshotMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_bid()->MergeFrom(from._internal_bid());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_ask()->MergeFrom(from._internal_ask());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _this->_internal_mutable_last()->MergeFrom(from._internal_last());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000008U)) {
      _this->_internal_mutable_delta()->MergeFrom(from._internal_delta());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000010U)) {
      _this->_internal_mutable_gamma()->MergeFrom(from._internal_gamma());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000020U)) {
      _this->_internal_mutable_theta()->MergeFrom(from._internal_theta());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000040U)) {
      _this->_internal_mutable_vega()->MergeFrom(from._internal_vega());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000080U)) {
      _this->_internal_mutable_iv()->MergeFrom(from._internal_iv());
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00001f00U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (!from._internal_portfolio_name().empty()) {
        _this->_internal_set_portfolio_name(from._internal_portfolio_name());
      } else {
        if (_this->_impl_.portfolio_name_.IsDefault()) {
          _this->_internal_set_portfolio_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (from._internal_datetime_seconds() != 0) {
        _this->_impl_.datetime_seconds_ = from._impl_.datetime_seconds_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_underlying_bid()) != 0) {
        _this->_impl_.underlying_bid_ = from._impl_.underlying_bid_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_underlying_ask()) != 0) {
        _this->_impl_.underlying_ask_ = from._impl_.underlying_ask_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_underlying_last()) != 0) {
        _this->_impl_.underlying_last_ = from._impl_.underlying_last_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PortfolioSnapshotMsg::CopyFrom(const PortfolioSnapshotMsg& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:otrader.PortfolioSnapshotMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PortfolioSnapshotMsg::InternalSwap(PortfolioSnapshotMsg* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.bid_.InternalSwap(&other->_impl_.bid_);
  _impl_.ask_.InternalSwap(&other->_impl_.ask_);
  _impl_.last_.InternalSwap(&other->_impl_.last_);
  _impl_.delta_.InternalSwap(&other->_impl_.delta_);
  _impl_.gamma_.InternalSwap(&other->_impl_.gamma_);
  _impl_.theta_.InternalSwap(&other->_impl_.theta_);
  _impl_.vega_.InternalSwap(&other->_impl_.vega_);
  _impl_.iv_.InternalSwap(&other->_impl_.iv_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.portfolio_name_, &other->_impl_.portfolio_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.underlying_last_)
      + sizeof(PortfolioSnapshotMsg::_impl_.underlying_last_)
      - PROTOBUF_FIELD_OFFSET(PortfolioSnapshotMsg, _impl_.datetime_seconds_)>(
          reinterpret_cast<char*>(&_impl_.datetime_seconds_),
          reinterpret_cast<char*>(&other->_impl_.datetime_seconds_));
}

::google::protobuf::Metadata PortfolioSnapshotMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace otrader
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_marketdata_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
